<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Page</name>
   <tag></tag>
   <elementGuidId>1d3a0c27-9d49-4b21-856c-884ee9eadcef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='connection_forms--details--view_page_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection_forms--details--view_page_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4234098a-03f4-40cb-8760-631eb5c6f033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss273</value>
      <webElementGuid>4dfb31a0-3fd4-4812-9678-fb124758dedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hc-stage.saddleback.com/public/connection-form/72/cris-test-connection-form</value>
      <webElementGuid>b9b79e97-0e18-45f2-95b7-a1f39af5995c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_forms--details--view_page_link</value>
      <webElementGuid>60a4e989-691d-441a-81cd-adbd08be302f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>31df3239-0622-4d44-83fe-8d8a1764d802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>89d77ca3-041a-4586-8975-bf147fbeeb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Page</value>
      <webElementGuid>83c147c1-062d-4355-9aa5-d21968ee4355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_forms--details--view_page_link&quot;)</value>
      <webElementGuid>117215e6-48ff-4098-a11a-9ad901eaf2de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='connection_forms--details--view_page_link']</value>
      <webElementGuid>09d39b20-ecd0-4e14-bdcc-54b64c920b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div[2]/div/div/div/div/div[2]/div/div[7]/div/div/ul/li/a</value>
      <webElementGuid>d3dbf54b-d751-4de0-b2de-534ead5245a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Page')]</value>
      <webElementGuid>3b891560-fcf9-4ff5-a49c-4209287eee13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hc-stage.saddleback.com/public/connection-form/72/cris-test-connection-form')]</value>
      <webElementGuid>36411dd0-d56a-4148-a5d6-a41571ff5858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>e928c448-96ef-4059-a1a8-b444898eed47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hc-stage.saddleback.com/public/connection-form/72/cris-test-connection-form' and @id = 'connection_forms--details--view_page_link' and (text() = 'View Page' or . = 'View Page')]</value>
      <webElementGuid>d3e2885d-720f-49cc-8faf-8b608148c556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
