<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cris Test Connection Form</name>
   <tag></tag>
   <elementGuidId>db549bf3-3239-4dcc-941a-00130d10566c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cmui.grid--column.jss45.jss288</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fac73bf9-6089-4b35-8b7d-d18dece246f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui grid--column jss45 jss288</value>
      <webElementGuid>4c7eaaa3-d626-44b9-babb-b53d8d3651a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui-grid_column</value>
      <webElementGuid>6aa4ba5e-9ea7-47f6-a973-136335ba5721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cris Test Connection Form</value>
      <webElementGuid>383030c3-34a4-4019-bfa4-d4aaab3e77f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_0&quot;)/div[@class=&quot;cmui grid jss7 jss286 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 jss288&quot;]</value>
      <webElementGuid>557da1c1-2e8c-412e-ae99-7956b287133d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_0']/div/div[2]</value>
      <webElementGuid>2bc87682-f264-4272-a25b-799797a9cebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]</value>
      <webElementGuid>fcaf8a01-1d2a-4d75-878b-8ada3cb068ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cris Test Connection Form' or . = 'Cris Test Connection Form')]</value>
      <webElementGuid>32b5ff64-39b7-45a0-8f6c-f9ba8793f8b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
