<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ui image image-avatar image-avatar-person</name>
   <tag></tag>
   <elementGuidId>e1e3dade-e4af-441e-840e-82891004aec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-3--value']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-3--value > div.Select-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4f6cc99-d668-4450-a7db-2f30babe0e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-value</value>
      <webElementGuid>d0b03655-dda4-445e-93d2-ccc185ba44fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui-image</value>
      <webElementGuid>8d48d613-5792-4b1d-aa4b-0ab1d056d89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-3--value&quot;)/div[@class=&quot;Select-value&quot;]</value>
      <webElementGuid>722a0818-3bf0-4784-8539-5a18cf8d5113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-3--value']/div</value>
      <webElementGuid>f7ca73d6-f0b4-4b7a-a75d-943722ecb09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>dced234d-6ade-4fd2-8ea1-1d8df35e5d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='person-list-18613-row']/td/div</value>
      <webElementGuid>112cfe3a-1368-433e-aaf2-90eed2eda233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div</value>
      <webElementGuid>9f49a7f5-43b0-4092-ba03-5ea512aef1d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
