<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Whitney  Kelmp</name>
   <tag></tag>
   <elementGuidId>df25cb4e-0b14-405d-95f6-d7b9ce01f7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/main/div/section/div/div/div/table/tbody/tr/td[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.jss888</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3b31559-6cab-4560-a4b8-fa3f85757c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss888</value>
      <webElementGuid>ffe183b8-cc41-432a-99ea-de5cdbad36f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Whitney  Kelmp</value>
      <webElementGuid>8ab71431-e065-4291-9303-18745acf3512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss285 jss848 jss824 jss846 ministry-occurrence-schedule-wrap page-has_action_bar&quot;]/div[@class=&quot;cmui container jss682 ui page--container jss681&quot;]/section[@class=&quot;cmui content jss685 ui page--content jss684&quot;]/div[@class=&quot;view-container&quot;]/div[@class=&quot;view-scrollbar padding-bottom-2x&quot;]/div[@class=&quot;roster-container&quot;]/table[@class=&quot;ui jss876 table table-basic table-font-size-xsmall table-selectable table-stretch-very&quot;]/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;table-row table-row-clickable&quot;]/td[@class=&quot;table-cell&quot;]/div[@class=&quot;jss887&quot;]/div[@class=&quot;jss888&quot;]</value>
      <webElementGuid>dd5ea392-bfb6-4ab1-b067-00526d9af9f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div/div/div/table/tbody/tr/td[3]/div/div</value>
      <webElementGuid>a7cb9d7f-87bd-4637-b088-967d59f4a219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div</value>
      <webElementGuid>e90ba770-9d88-4ffa-b0fc-31fca33bb9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Whitney  Kelmp' or . = 'Whitney  Kelmp')]</value>
      <webElementGuid>bb1a2ad6-2020-4452-9f13-1f571da5f72a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
