<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputjourneys_list_page--template_subtitle</name>
   <tag></tag>
   <elementGuidId>c7b385a2-35c7-483a-8bd8-1777592c82d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='journeys_list_page--template_subtitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#journeys_list_page--template_subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a36d1cae-4bda-4ffc-93a6-7e8ee4f410c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>journeys_list_page--template_subtitle</value>
      <webElementGuid>097b7221-d4db-49c1-99cd-edddc8f7ec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c68e0a04-1287-43bf-9753-716516210bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cad1fde-4a7b-4f99-be45-6e7644c27c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--template_subtitle&quot;)</value>
      <webElementGuid>dcd8f090-6741-4183-b708-b8c77ebc4b19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='journeys_list_page--template_subtitle']</value>
      <webElementGuid>b5186f11-a4e7-4ec0-84b7-fcdc1fe054d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>13d0efbc-f6ad-46e4-a6fd-05861a0c7a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'journeys_list_page--template_subtitle' and @type = 'text']</value>
      <webElementGuid>0200e0ea-c79f-4a1a-9108-698512601bb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
