<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputconnection_form_public--personal_form__251b9d</name>
   <tag></tag>
   <elementGuidId>a961ac4a-cb3e-4aee-baec-44f5af62cd43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection_form_public--personal_form_field_lastname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection_form_public--personal_form_field_lastname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48fac13e-d6ed-42d2-92d4-cbde9d5a2f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_form_public--personal_form_field_lastname</value>
      <webElementGuid>b659b713-315e-45fd-8a38-b71ce9ca69af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5b867b4-609a-4db5-8661-40eb8e0f1d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_form_public--personal_form_field_lastname&quot;)</value>
      <webElementGuid>da838bc9-067e-4ec3-835e-2a0eed99256f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection_form_public--personal_form_field_lastname']</value>
      <webElementGuid>3c00b558-aae6-43e6-bc18-5196d5c28074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div/div/div[3]/div/div[3]/div/input</value>
      <webElementGuid>4d05291a-ea9c-466d-bed6-5899f4e185ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>965404af-55b4-4b37-bdc7-bc10e5f8339f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection_form_public--personal_form_field_lastname' and @type = 'text']</value>
      <webElementGuid>aac3c38a-1104-41eb-973f-578900358643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
