<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Did you complete Class 101check</name>
   <tag></tag>
   <elementGuidId>05caf060-e352-4c5c-9f97-5df702032748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='connection_form_public--question_field_7518']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.checkbox-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cf9f4dbc-1463-4715-9b93-46f9188cc904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-label</value>
      <webElementGuid>2357b913-fe97-44d1-a317-fa411a665605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Did you complete Class 101?check</value>
      <webElementGuid>880d8e76-547a-4af1-8b16-e20296fce45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_form_public--question_field_7518&quot;)/label[@class=&quot;checkbox-label&quot;]</value>
      <webElementGuid>43158541-4cf6-47bd-b327-ba2ec42b7ae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='connection_form_public--question_field_7518']/label</value>
      <webElementGuid>ee53aad3-195a-4967-a47d-f82433a07129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/label</value>
      <webElementGuid>33dff655-9df8-4039-a0a1-409d1bfdf9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Did you complete Class 101?check' or . = 'Did you complete Class 101?check')]</value>
      <webElementGuid>b730d9c1-e79b-42c0-a059-51b03350a33e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
