<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_templateWeb HeaderimageUploadphone-_5caeb1</name>
   <tag></tag>
   <elementGuidId>7b021b70-d399-432c-9c52-e95a559544d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/section</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.ui.jss366.drawer--content.journeys_list_page--content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>1eb6d4ff-8dbc-4053-8d61-2d5646155227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui jss366 drawer--content journeys_list_page--content</value>
      <webElementGuid>450203d5-954e-465a-a4f0-c35d0e961741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui-drawer_content</value>
      <webElementGuid>04f738c8-28dc-486b-9925-246f826f63b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>templateWeb HeaderimageUploadphone-cellCompanion App HeaderimageUploadThumbnailimageUploadimageUpload for alldeleteClear allJourney DetailsName *Public Name *SubtitleDescriptionCampus Ownership *AnaheimAutomatedCampusBerlinBreaBryant's Test CampusBuena ParkBuenos AiresCampusToCreateEvent01CampusToCreateEvent02CampusToUpdateEvent01CoronaDana PointEaganEastvaleExtensionsGarrett's Test CampusGranadaHong KongHuntington BeachIrvine NorthIrvine SouthLaguna WoodsLake ForestLake Forest Chinese CommunityLos AngelesNew CampusNewport MesaNorthridge HGOnline CommunityPrescottQA ME Auto Test CampusQA ME Manual Test CampusQA Test Campus 1.23.0Rancho CapistranoSA Nepal Test1SA3SacramentoSaddleback en EspañolSan Antonio - Test1San Antonio - Test2San ClementeSan DiegoSanta RosaSouth BayST Campus TestStockholm CampusTemeculaVancouverWhittierSelectCategory *20s/30sBaptismDiscipleshipWorshipSelectTagsClassAdult911SKFitnessSelect...chevron-downJourney OwnersJourney owners are a individuals that edit and oversee this journey.Owner  *CFCris FranciscoLake Forestcrisf@saddleback.comChangeAre you sure?YesNoCo-OwnerplusAdd Co-Owner</value>
      <webElementGuid>91a653ce-a26b-4cba-9051-61bcd2859e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;safari&quot;]/body[@class=&quot;drawer-open drawer-dimmers&quot;]/div[6]/div[@class=&quot;ui drawer jss201 journeys_list_page--add_drawer drawer-is_modal drawer-has_title_bar drawer-has_action_bar&quot;]/div[@class=&quot;drawer-container&quot;]/div[1]/div[1]/div[@class=&quot;drawer-container-inner&quot;]/section[@class=&quot;ui jss366 drawer--content journeys_list_page--content&quot;]</value>
      <webElementGuid>45745f20-d065-4909-aab8-d3223f0ccfc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/section</value>
      <webElementGuid>c449f03d-27b9-45eb-909a-8f787275f55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = concat(&quot;templateWeb HeaderimageUploadphone-cellCompanion App HeaderimageUploadThumbnailimageUploadimageUpload for alldeleteClear allJourney DetailsName *Public Name *SubtitleDescriptionCampus Ownership *AnaheimAutomatedCampusBerlinBreaBryant&quot; , &quot;'&quot; , &quot;s Test CampusBuena ParkBuenos AiresCampusToCreateEvent01CampusToCreateEvent02CampusToUpdateEvent01CoronaDana PointEaganEastvaleExtensionsGarrett&quot; , &quot;'&quot; , &quot;s Test CampusGranadaHong KongHuntington BeachIrvine NorthIrvine SouthLaguna WoodsLake ForestLake Forest Chinese CommunityLos AngelesNew CampusNewport MesaNorthridge HGOnline CommunityPrescottQA ME Auto Test CampusQA ME Manual Test CampusQA Test Campus 1.23.0Rancho CapistranoSA Nepal Test1SA3SacramentoSaddleback en EspañolSan Antonio - Test1San Antonio - Test2San ClementeSan DiegoSanta RosaSouth BayST Campus TestStockholm CampusTemeculaVancouverWhittierSelectCategory *20s/30sBaptismDiscipleshipWorshipSelectTagsClassAdult911SKFitnessSelect...chevron-downJourney OwnersJourney owners are a individuals that edit and oversee this journey.Owner  *CFCris FranciscoLake Forestcrisf@saddleback.comChangeAre you sure?YesNoCo-OwnerplusAdd Co-Owner&quot;) or . = concat(&quot;templateWeb HeaderimageUploadphone-cellCompanion App HeaderimageUploadThumbnailimageUploadimageUpload for alldeleteClear allJourney DetailsName *Public Name *SubtitleDescriptionCampus Ownership *AnaheimAutomatedCampusBerlinBreaBryant&quot; , &quot;'&quot; , &quot;s Test CampusBuena ParkBuenos AiresCampusToCreateEvent01CampusToCreateEvent02CampusToUpdateEvent01CoronaDana PointEaganEastvaleExtensionsGarrett&quot; , &quot;'&quot; , &quot;s Test CampusGranadaHong KongHuntington BeachIrvine NorthIrvine SouthLaguna WoodsLake ForestLake Forest Chinese CommunityLos AngelesNew CampusNewport MesaNorthridge HGOnline CommunityPrescottQA ME Auto Test CampusQA ME Manual Test CampusQA Test Campus 1.23.0Rancho CapistranoSA Nepal Test1SA3SacramentoSaddleback en EspañolSan Antonio - Test1San Antonio - Test2San ClementeSan DiegoSanta RosaSouth BayST Campus TestStockholm CampusTemeculaVancouverWhittierSelectCategory *20s/30sBaptismDiscipleshipWorshipSelectTagsClassAdult911SKFitnessSelect...chevron-downJourney OwnersJourney owners are a individuals that edit and oversee this journey.Owner  *CFCris FranciscoLake Forestcrisf@saddleback.comChangeAre you sure?YesNoCo-OwnerplusAdd Co-Owner&quot;))]</value>
      <webElementGuid>b8629617-d45d-4962-a2cd-7da399ce8af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
