<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Membership Settings</name>
   <tag></tag>
   <elementGuidId>7ae85d13-27ca-4baf-a8b5-6630c8874d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='settings--section_nav_button_membershipSettings']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#settings--section_nav_button_membershipSettings > span.button-inner-container.jss353</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c008020d-d186-477f-91ef-52c1acb4de56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Membership Settings</value>
      <webElementGuid>c57359ba-d76f-4792-aa51-595a0426ba32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings--section_nav_button_membershipSettings&quot;)/span[@class=&quot;button-inner-container jss353&quot;]</value>
      <webElementGuid>b3a14392-8ba3-45ff-8cfc-4a65ccc72881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner-container jss353</value>
      <webElementGuid>49cb2167-2559-4eb3-9a6e-9d7376afaaa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='settings--section_nav_button_membershipSettings']/span</value>
      <webElementGuid>7308b9e5-09c5-414c-87a8-6756f2a69c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/button[3]/span</value>
      <webElementGuid>755df531-6c85-4528-87b5-78aa5125605f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Membership Settings' or . = 'Membership Settings')]</value>
      <webElementGuid>2dbeebc3-bbc3-4ea9-a701-34d5c2791aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='settings--section_nav_button_membershipSettings']/span/span[2]</value>
      <webElementGuid>8186baf9-3647-4cba-869d-926b0ce19a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span/span[2]</value>
      <webElementGuid>5d1346fe-c0a8-4ede-bf1e-f719e0e83526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
