<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Unpublish</name>
   <tag></tag>
   <elementGuidId>a3a07173-85f8-417a-9484-8d57a64c0a5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='connection_forms--details--publish_unpublish_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection_forms--details--publish_unpublish_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e01d0cc-02b9-48be-9f90-b255b6c28783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui a jss358 jss273</value>
      <webElementGuid>905f2647-a51b-4de8-bdd2-0a2c835267e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_forms--details--publish_unpublish_link</value>
      <webElementGuid>183071ec-bc6f-4714-aae5-87280d91a1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af96aa0d-499a-4802-b7da-6972dde07b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bfa91dc7-e4a7-4a8f-a880-ddd2f8d81ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unpublish</value>
      <webElementGuid>9fcac38e-8f09-4e81-bb40-eb2525ea415e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_forms--details--publish_unpublish_link&quot;)</value>
      <webElementGuid>9ed5b490-70fa-45fc-8845-6002c6b16343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='connection_forms--details--publish_unpublish_link']</value>
      <webElementGuid>95c30935-299f-40ef-b72a-eb63bf20db12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div[2]/div/div/div/div/div[2]/div/div[7]/div/div/ul/li[3]/div/div/span</value>
      <webElementGuid>2021bb7c-fedc-4a81-9dbf-a3f553605cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/span</value>
      <webElementGuid>3b62c8f2-7581-421a-8832-a1693127d570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'connection_forms--details--publish_unpublish_link' and (text() = 'Unpublish' or . = 'Unpublish')]</value>
      <webElementGuid>6c0f4507-d40d-4040-86f5-b55f98f2c718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
