<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Communications</name>
   <tag></tag>
   <elementGuidId>83a27979-9a49-4b63-b041-c43d3c9dfc2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-navigation_tab--key-item-5']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-navigation_tab--key-item-5 > span.MuiTypography-root.jss423.navigation_sectional_tabs--tab-label.MuiTypography-h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7789f6e1-1d46-4803-b24e-13063123e3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root jss423 navigation_sectional_tabs--tab-label MuiTypography-h5</value>
      <webElementGuid>49947dd0-47f5-480c-b24c-aff6b9599e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Communications</value>
      <webElementGuid>42f056d6-9396-421b-9fa7-9a0e8b61e814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-navigation_tab--key-item-5&quot;)/span[@class=&quot;MuiTypography-root jss423 navigation_sectional_tabs--tab-label MuiTypography-h5&quot;]</value>
      <webElementGuid>84bdc7d7-ad29-43e0-99ed-83c4f4b3db2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='tab-navigation_tab--key-item-5']/span</value>
      <webElementGuid>65c0385d-527e-47bc-bc46-23259439a01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]/span</value>
      <webElementGuid>d133312e-a7df-48e5-9637-b207d1265614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Communications' or . = 'Communications')]</value>
      <webElementGuid>f462b6d2-e5fb-4c87-a578-bc920653be86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='tab-navigation_tab--key-item-3']/span</value>
      <webElementGuid>871bd5a1-91c3-4180-994a-9c2324c5db46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span</value>
      <webElementGuid>0649f057-f4d0-4a6a-b02d-3b6980e11241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
