<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Accounting2Accounting2Accounting2Accounting2</name>
   <tag></tag>
   <elementGuidId>c25ed0fd-705e-4c94-8250-d819570a2047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ui-table_row--ministry_central_row_1147']/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.font-weight-semibold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fe5e1112-83bd-4a06-bb32-dd61dc612ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-semibold</value>
      <webElementGuid>fb06be91-d33e-4364-aa3a-217559e22885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accounting2Accounting2Accounting2Accounting2</value>
      <webElementGuid>46aa0493-96eb-4c09-b0a1-d7691a06bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-table_row--ministry_central_row_1147&quot;)/td[@class=&quot;table-cell table-cell-font-size-small table-cell-twelve table-cell-name&quot;]/span[@class=&quot;font-weight-semibold&quot;]</value>
      <webElementGuid>218cd8f2-e20e-4ba6-8178-81ca39322c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ui-table_row--ministry_central_row_1147']/td[2]/span</value>
      <webElementGuid>459344cc-f6f9-429b-ad3b-3761ef9fdb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>ea005c1f-8502-41c3-842e-e5da803dbe19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Accounting2Accounting2Accounting2Accounting2' or . = 'Accounting2Accounting2Accounting2Accounting2')]</value>
      <webElementGuid>abb07a18-ba34-4c24-a208-a282688f944e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
