<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Katalon Test</name>
   <tag></tag>
   <elementGuidId>55d92bff-096f-4c69-966c-63eb3b7fe3e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='journeys_list_page--description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#journeys_list_page--description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>67989181-2c52-465f-bf16-3d3f4c1b056e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>journeys_list_page--description</value>
      <webElementGuid>19aac6fd-f9f6-431c-869c-4fcd2bebd251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Test</value>
      <webElementGuid>c6dec23a-429e-48e7-842b-cc08a307e284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--description&quot;)</value>
      <webElementGuid>a6c23b48-f51d-4977-a3e2-fc35c8ee5fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='journeys_list_page--description']</value>
      <webElementGuid>15024623-6a9a-4ba9-9b7c-3cbe8aef33f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b1520ddf-3dc5-495a-9004-a966d36e71b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'journeys_list_page--description' and (text() = 'Katalon Test' or . = 'Katalon Test')]</value>
      <webElementGuid>8463f636-9f08-4e94-9271-2157d5ca0f69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
