<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Katalon Test Descript</name>
   <tag></tag>
   <elementGuidId>0b0105f8-392f-49db-8a8c-634b23c9da1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='journeys_list_page--description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#journeys_list_page--description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5393fab9-801d-456f-a63c-520f6d9cadd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>journeys_list_page--description</value>
      <webElementGuid>32885beb-56c0-4695-8fae-def2c2751bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Test Descript</value>
      <webElementGuid>452d5f51-25d6-4ed3-bbad-908f9cf3d8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--description&quot;)</value>
      <webElementGuid>55c7b7e6-8c5c-4cd7-9bdf-ed48905af649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='journeys_list_page--description']</value>
      <webElementGuid>51d46a1d-5492-4045-a71b-104d9d0e9120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c9f04eaf-2116-45a3-b62f-8b03e37d0a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'journeys_list_page--description' and (text() = 'Katalon Test Descript' or . = 'Katalon Test Descript')]</value>
      <webElementGuid>5d9bc1c7-56bf-4fc7-a21a-a41a7a58d343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
