<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Katalon Test D</name>
   <tag></tag>
   <elementGuidId>460f6df3-a8ef-48bc-976d-0c3a75efe106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='journeys_list_page--description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#journeys_list_page--description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>73c1b5c7-6064-4dd2-8bf1-31a32b2c64d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>journeys_list_page--description</value>
      <webElementGuid>ab70bb98-2ad6-4ff6-9058-02e56eb7ed6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Test D</value>
      <webElementGuid>6b6429e1-faa3-47cb-bf51-2434f3ce1825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--description&quot;)</value>
      <webElementGuid>d9d5ef9c-03e8-4c28-9ada-b12a874422e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='journeys_list_page--description']</value>
      <webElementGuid>69c06f08-8ba2-4224-9927-3635fa062573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>312b5713-763b-4bee-84f3-dc491614dbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'journeys_list_page--description' and (text() = 'Katalon Test D' or . = 'Katalon Test D')]</value>
      <webElementGuid>942cd391-59e1-4e20-be3a-c93636ceafaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
