<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use_icon-use-path</name>
   <tag></tag>
   <elementGuidId>197474a5-c117-4bd3-93e9-3d9b1fa1f9f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Select.is-focused.is-open.Select--multi > div.Select-control > span.Select-arrow-zone > div > div.cmui.ui.icon.icon-chevron-down.icon-align-left.icon-color-primary.icon-compact > svg > g > use.icon-use-path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>29f47379-5af8-4d4b-aef0-f46e95d79a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-use-path</value>
      <webElementGuid>68f4d1ad-14a8-44b4-ab21-822b8d68a0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>#icon-svg-path-chevron-down-5231951073</value>
      <webElementGuid>5d083505-80aa-404d-9c89-109e1f4809f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--field_tags&quot;)/div[@class=&quot;Select is-focused is-open Select--multi&quot;]/div[@class=&quot;Select-control&quot;]/span[@class=&quot;Select-arrow-zone&quot;]/div[1]/div[@class=&quot;cmui ui icon icon-chevron-down icon-align-left icon-color-primary icon-compact&quot;]/svg[1]/g[1]/use[@class=&quot;icon-use-path&quot;]</value>
      <webElementGuid>2177192e-640a-4c0f-82f2-613df8d8ffce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
