<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Communication Name</name>
   <tag></tag>
   <elementGuidId>247b4915-dc61-4af4-9993-afad9721c133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#communication_primary_details_edit_modal--name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='communication_primary_details_edit_modal--name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Give a name to this communication...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33056f07-bfc3-4c8e-b799-5964a1f9bb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>communication_primary_details_edit_modal--name</value>
      <webElementGuid>e07233b8-2513-470f-8883-91b82e945914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give a name to this communication...</value>
      <webElementGuid>296da52d-120a-40a9-a755-84b1baeac99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>326c83d6-792d-4a0d-809a-1be83505eef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Testing </value>
      <webElementGuid>9ca86eaa-6c7f-45b5-9a38-99dbdb17386b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;communication_primary_details_edit_modal--name&quot;)</value>
      <webElementGuid>76c864e0-4179-4435-b6c5-91eafecda763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='communication_primary_details_edit_modal--name']</value>
      <webElementGuid>f59e365b-edd1-415f-a6fe-309c80c29b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>62771c4b-7bef-4280-9ca5-c862b1d07244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'communication_primary_details_edit_modal--name' and @placeholder = 'Give a name to this communication...' and @type = 'text']</value>
      <webElementGuid>632d84b3-2120-40a9-8bab-307526ff50b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
