<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Description</name>
   <tag></tag>
   <elementGuidId>0158abf0-342a-49ed-9133-9096ea3607eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#communication_primary_details_edit_modal--description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='communication_primary_details_edit_modal--description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Give description to this communication...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>261c43e4-c8ce-4087-a308-fabeb8f6d80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>communication_primary_details_edit_modal--description</value>
      <webElementGuid>941dc0dc-7ac3-41a1-833b-99340862dfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>92a6a0c3-d2b0-4db6-b433-86c1e0a4fa68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give description to this communication...</value>
      <webElementGuid>efd4f597-7f13-471b-93d2-145bba01ad16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing 1 Description </value>
      <webElementGuid>ee846fce-ae2b-4400-ae45-f961ece01bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;communication_primary_details_edit_modal--description&quot;)</value>
      <webElementGuid>52f417b4-2c7a-40f8-8c5c-bbf999f44f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='communication_primary_details_edit_modal--description']</value>
      <webElementGuid>0bcaa6b2-6458-4395-b6da-f22da499d183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::textarea[1]</value>
      <webElementGuid>fbae018c-85e9-4a23-9252-f0919fabe555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Name'])[1]/following::textarea[1]</value>
      <webElementGuid>848b6e5f-75cb-4a3b-84bb-a15c696bcf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campus'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5f0ef87b-b4dc-461c-b831-86598cfdfa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABCD'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8ba94d88-33a9-4726-9266-1adcf0c6836e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing 1 Description']/parent::*</value>
      <webElementGuid>ebdb9287-a3cc-4006-9b45-02e77da4a5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ee6f70b9-5632-44ee-936d-2e1daf0cd454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'communication_primary_details_edit_modal--description' and @placeholder = 'Give description to this communication...' and (text() = 'Testing 1 Description ' or . = 'Testing 1 Description ')]</value>
      <webElementGuid>365ce92c-b5a2-478d-b0cb-592bf5b2434f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
