<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputjourneys_list_page--template_public_name</name>
   <tag></tag>
   <elementGuidId>9b787ab3-49f1-4e98-9ecd-a2cf803b6bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='journeys_list_page--template_public_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#journeys_list_page--template_public_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5198ceff-bfe6-40b5-9027-3bb2d2012774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>journeys_list_page--template_public_name</value>
      <webElementGuid>11872342-d79f-49bf-83e7-118a0f5bc011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c334ae89-61e8-4153-8d7e-d5630e068146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09c11dd4-ea1d-4bb4-8959-aae58166d9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--template_public_name&quot;)</value>
      <webElementGuid>eb2de91d-aa75-4fbb-8df8-155a61559574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='journeys_list_page--template_public_name']</value>
      <webElementGuid>011e2053-ff52-4bcd-92fe-73d2964de278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>156e98c7-5a5e-4f79-b9e3-79b95ba1d075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'journeys_list_page--template_public_name' and @type = 'text']</value>
      <webElementGuid>07def264-ea41-4f54-86e4-8a3aca0f2b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
