<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_configuration-2Edit Details</name>
   <tag></tag>
   <elementGuidId>f49e1786-b0cd-431e-b137-a18810f51342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='journeys_list_page--edit_details_button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.button-inner-container.jss244</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c4a8a3e-e7a4-4712-baee-fd70118df6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner-container jss244</value>
      <webElementGuid>2e8e66da-2701-4bec-896c-0a94d2adf0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>configuration-2Edit Details</value>
      <webElementGuid>02b344e9-8068-4fb6-927d-5cb7cf30a614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--edit_details_button&quot;)/span[@class=&quot;button-inner-container jss244&quot;]</value>
      <webElementGuid>41a0f840-fb9a-46df-b114-810da0167715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='journeys_list_page--edit_details_button']/span</value>
      <webElementGuid>f349b1cc-6b0c-4c07-8497-4d7864244fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div/button/span</value>
      <webElementGuid>872e72c8-8de4-4c78-97d7-6815552f34cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'configuration-2Edit Details' or . = 'configuration-2Edit Details')]</value>
      <webElementGuid>1884db1e-19aa-41b9-bf7e-78330cccddb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
