<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Maximum Age Input Field</name>
   <tag></tag>
   <elementGuidId>a006822b-8f9f-4666-b830-109759ed5de6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxAge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Max Age&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d4cbb28-b8ec-4d24-a807-dc995603b281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAge</value>
      <webElementGuid>a352bb18-13d1-4b45-b5b4-e3a964996280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>16980fe2-85da-4eb5-b8d7-c093ce80528e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0facb8db-ca2c-432a-92a1-2d1a3de65519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAge&quot;)</value>
      <webElementGuid>18bde7d1-f5fb-4156-a907-ecd3f3a2bc46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAge']</value>
      <webElementGuid>e9842d1c-49fa-4c23-b825-b0223853c6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>b620c8b5-511f-4087-b24a-6667000b0d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAge' and @type = 'number']</value>
      <webElementGuid>4df44c93-3c8b-44d0-a8ee-1caaf23a5659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
