<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email Text Field</name>
   <tag></tag>
   <elementGuidId>9eb8ea1b-7d37-446d-8f62-063aebd5db2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection_form_public--contact_form_field_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection_form_public--contact_form_field_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f60b39b5-388d-49d6-a3fb-ae04e2f1a4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_form_public--contact_form_field_email</value>
      <webElementGuid>0f28ffbd-6406-4cec-8e68-2479ecd697ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ed762a8-b8a2-454b-b3eb-5551ee2e9677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infoCardPopup683&quot;)/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;connection-form-container&quot;]/div[@class=&quot;connection-form&quot;]/div[@class=&quot;widget-content&quot;]/div[@class=&quot;connection-form2&quot;]/div[@class=&quot;connection-form724&quot;]/div[@class=&quot;cmui grid connection-form527 connection-form725 connection-form555&quot;]/div[@class=&quot;cmui grid--column connection-form565 connection-form726 connection-form588&quot;]/div[@class=&quot;ui input connection-form727 input-fluid input-focused input-type-text&quot;]/input[@id=&quot;connection_form_public--contact_form_field_email&quot;]</value>
      <webElementGuid>be56f8ee-4889-4edc-9c34-63a9d3e22b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection_form_public--contact_form_field_email']</value>
      <webElementGuid>bda622e6-0540-49a5-bb7f-1b9c98b00f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='infoCardPopup683']/div/div/div[2]/div/div/div[3]/div/div[2]/div/input</value>
      <webElementGuid>fc882e6d-c602-4a02-908e-c2f2e0bd575f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>73b838e4-93fd-41eb-a820-cb59b3824346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection_form_public--contact_form_field_email' and @type = 'text']</value>
      <webElementGuid>5fa71284-5cbe-48fc-815c-165407bb6cc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
