<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Home</name>
   <tag></tag>
   <elementGuidId>4f81e02b-db3a-4e08-a6c7-f6a870729a1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Home' or . = 'Home')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.label.connection-form737</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6c8b16d0-16b5-4a60-9742-997ba188e712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label connection-form737</value>
      <webElementGuid>a3eb94e5-d278-4b75-99af-eb5c4a61fa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>27576cae-754d-4d7f-a08f-835525cd28a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infoCardPopup683&quot;)/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;connection-form-container&quot;]/div[@class=&quot;connection-form&quot;]/div[@class=&quot;widget-content&quot;]/div[@class=&quot;connection-form2&quot;]/div[@class=&quot;connection-form724&quot;]/div[@class=&quot;cmui grid connection-form527 connection-form725 connection-form555&quot;]/div[@class=&quot;cmui grid--column connection-form565 connection-form731 connection-form588 connection-form596 connection-form566&quot;]/div[@class=&quot;cmui grid--column connection-form565 connection-form580&quot;]/div[@class=&quot;ui radio connection-form739&quot;]/label[@class=&quot;label connection-form737&quot;]</value>
      <webElementGuid>75ba398b-c4ff-4852-9953-c81c23cd9c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='infoCardPopup683']/div/div/div[2]/div/div/div[3]/div/div[4]/div/div/label</value>
      <webElementGuid>181e8448-bd37-4c2e-af42-87ee4632a8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/label</value>
      <webElementGuid>0be37ff4-54e4-437b-af19-e4dd2421c9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>7ced20c4-4117-45de-953a-d9d3e41c1868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
