<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phone Text Field</name>
   <tag></tag>
   <elementGuidId>f9443b83-a810-46bb-b978-353d1feae8b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection_form_public--contact_form--field_phone_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.react-phone-number-input__row > #connection_form_public--contact_form--field_phone_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>711fe3a3-af59-4de9-98cb-db05c0a3361c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>492b699f-28ea-4f46-b2b1-97c8e9fe7b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e44215a4-be23-4540-9c73-19fdaaa3d79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_form_public--contact_form--field_phone_input</value>
      <webElementGuid>810c9064-517b-4be8-b80f-cb00b4817dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>21457de5-ec18-41ea-b1b5-8c63af5648fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-phone-number-input__input react-phone-number-input__phone react-phone-number-input__input--style react-phone-number-input__input--invalid react-phone-number-input__input--style--invalid</value>
      <webElementGuid>ef71df8b-2306-4641-8305-8a6a8c78001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>e0e89fea-f688-47ca-90b6-49bd7b5c507c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infoCardPopup683&quot;)/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;connection-form-container&quot;]/div[@class=&quot;connection-form&quot;]/div[@class=&quot;widget-content&quot;]/div[@class=&quot;connection-form2&quot;]/div[@class=&quot;connection-form724&quot;]/div[@class=&quot;cmui grid connection-form527 connection-form725 connection-form555&quot;]/div[@class=&quot;cmui grid--column connection-form565 connection-form730 connection-form588 connection-form596&quot;]/div[@id=&quot;connection_form_public--contact_form--field_phone_input&quot;]/div[@class=&quot;react-phone-number-input react-phone-number-input--focus react-phone-number-input--invalid&quot;]/div[@class=&quot;react-phone-number-input__row&quot;]/input[@id=&quot;connection_form_public--contact_form--field_phone_input&quot;]</value>
      <webElementGuid>27f80eeb-6b92-4173-b423-5a2ad3ebb26c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection_form_public--contact_form--field_phone_input']</value>
      <webElementGuid>08091745-04ca-4d0f-bb00-53ff08d1a13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='connection_form_public--contact_form--field_phone_input']/div/div/input</value>
      <webElementGuid>5ae3e4aa-ce12-418f-9465-4c7700da3ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div/input</value>
      <webElementGuid>d183f635-47b1-4047-9ae4-7dadbf0427f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'connection_form_public--contact_form--field_phone_input']</value>
      <webElementGuid>992f1c5a-a24d-4339-8dca-2b43ab4b1a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
