<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendee Search Bar</name>
   <tag></tag>
   <elementGuidId>97f1a82a-f400-462b-a370-16647f651b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='check_in_person_search--search_input' and not(@disabled)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#check_in_person_search--search_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e509b9d4-2c37-42ac-b7b6-9fb30d1da38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui--search_input</value>
      <webElementGuid>e753bc38-2abb-4133-b289-64c7b8e02819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check_in_person_search--search_input</value>
      <webElementGuid>5773e01b-1288-4368-b72b-14f7545b5653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by Name or Phone Number</value>
      <webElementGuid>c72f2350-d8b5-4f47-ba67-544a273d97f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8970a437-0098-4c94-a37c-61917a16c765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Q</value>
      <webElementGuid>86dd02a5-3ef7-439a-9475-5b3e34d47043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check_in_person_search--search_input&quot;)</value>
      <webElementGuid>6d01de90-9a6f-4b00-af43-5d3cd6ba0f0b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
