<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendee Checkboxes</name>
   <tag></tag>
   <elementGuidId>f7bfecd9-b070-4979-bf24-43850ba312b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui.checkbox.jss738 > label.checkbox-label > div.cmui.ui.icon.icon-check.icon-align-left.icon-color-primary.icon-compact.icon-inverse > svg > g > use.icon-use-path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='check_in_page--room_attendees']/descendant::tbody/tr/td/descendant::label[contains(@class,'checkbox')]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>2e26824d-cd2c-42e4-a97b-84879cecc1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-use-path</value>
      <webElementGuid>e6e7b7f3-38e9-40ca-b9f4-b48616e0a1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>#icon-svg-path-check-7619612357</value>
      <webElementGuid>7c30cd30-27fb-405b-b9c8-d91050252b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss237 jss608 check_in_page page-has_action_bar&quot;]/div[@class=&quot;check_in_page--room_attendees&quot;]/main[@class=&quot;ui page jss237 jss763 jss760 page-has_action_bar&quot;]/div[@class=&quot;cmui container jss653 ui page--container jss742 jss652&quot;]/section[@class=&quot;cmui content jss656 ui page--content jss743 jss655&quot;]/table[@class=&quot;ui jss664 table table-basic table-font-size-xsmall table-selectable jss761&quot;]/thead[@class=&quot;table-header&quot;]/tr[@class=&quot;table-row&quot;]/th[@class=&quot;table-header-cell table-cell&quot;]/span[1]/div[@class=&quot;jss736&quot;]/div[@class=&quot;ui checkbox jss738&quot;]/label[@class=&quot;checkbox-label&quot;]/div[@class=&quot;cmui ui icon icon-check icon-align-left icon-color-primary icon-compact icon-inverse&quot;]/svg[1]/g[1]/use[@class=&quot;icon-use-path&quot;]</value>
      <webElementGuid>b2d8636a-9b73-4bd2-8959-a169bccdfb76</webElementGuid>
   </webElementProperties>
</WebElementEntity>
