<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>General Room Button</name>
   <tag></tag>
   <elementGuidId>82f02f85-6ed5-4282-9dbb-f70e9b282c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='check_in_page--open_room_modal_open_general_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#check_in_page--open_room_modal_open_general_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f0a0e15-606b-45ed-aa66-27920d9e3c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss669</value>
      <webElementGuid>0c520ccb-38f8-4fed-83e8-3c17d4999204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check_in_page--open_room_modal_open_general_button</value>
      <webElementGuid>11fb0d20-8016-4432-af89-4fe0e979ede7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d028e83-309e-4e93-830a-7d14b79a5c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>478394a7-be99-454c-bef7-40ff3ef6268f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>team</value>
      <webElementGuid>680b2fe6-a483-42c9-a917-ae1ed58000e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check_in_page--open_room_modal_open_general_button&quot;)</value>
      <webElementGuid>0166e32f-6f5e-4572-b0cb-6440dfffc3b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
