<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Selected Connection Form</name>
   <tag></tag>
   <elementGuidId>993c8700-deae-4085-8063-fd84621eddba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection_form_drawer--action_bar_add_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='connection_form_drawer--action_bar_add_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2723bcb3-0fab-4466-87c9-fadf6987bbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b8cd4d4e-923a-4e50-b8e4-c511e7c4518f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui button jss207 jss411 jss215 jss206</value>
      <webElementGuid>414622cc-373d-4abf-90df-f2fbf1ba961b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_form_drawer--action_bar_add_button</value>
      <webElementGuid>47be9c10-a3d4-40b0-8a5e-35dfc6917948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38a23c2f-0ce4-4c59-9a16-fe32cf5375d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>2238026c-5270-41cf-b59c-5ec100182103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_form_drawer--action_bar_add_button&quot;)</value>
      <webElementGuid>cddf3978-8548-4319-b23b-1c5edc4c335f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='connection_form_drawer--action_bar_add_button']</value>
      <webElementGuid>acb54bec-7915-4a27-8727-3a71945da215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>5227492f-d590-4e66-bb18-e07eb40a1343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'connection_form_drawer--action_bar_add_button' and @type = 'button' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>494626e7-94b1-485f-99b5-7b986d94745e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
