<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Connection Form Search Bar</name>
   <tag></tag>
   <elementGuidId>bfb64a7b-8f17-4872-9a3a-ec7f114dce31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection_form_drawer--action_bar_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection_form_drawer--action_bar_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f095cc06-f648-4b7d-a73b-e407d897c8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui--search_input</value>
      <webElementGuid>71a7446d-906b-4c66-80bb-78bcb08c8e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_form_drawer--action_bar_search</value>
      <webElementGuid>30794f11-a8ef-46d2-80b3-2638c8f04c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>22abc30d-c810-4e1f-937c-08f26716459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>620076d6-bb5c-431b-8207-bf36d2315eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_form_drawer--action_bar_search&quot;)</value>
      <webElementGuid>dead108d-a167-45ef-b72e-24bec9951ba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection_form_drawer--action_bar_search']</value>
      <webElementGuid>d3f86bf2-d13e-47de-8262-d3259d826bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/header/div/div/div[2]/div/div/input</value>
      <webElementGuid>97a37dfd-3658-4811-a20e-15a02b629be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection_form_drawer--action_bar_search' and @placeholder = 'Search' and @type = 'text']</value>
      <webElementGuid>48329163-755f-4883-98b1-eae8af0fbad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
