<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First Service Companion Search Result</name>
   <tag></tag>
   <elementGuidId>94927a59-309f-4e96-b5dc-34024018c630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data_grid--table_page_cell_base-2_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='data_grid--table_page_cell_base-2_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>dd66ef01-8bb2-43fc-832c-659cbb9b3901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-cell</value>
      <webElementGuid>21053e75-cad9-4a95-a2f1-c89abd55ebb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data_grid--table_page_cell_base-2_0</value>
      <webElementGuid>b02cd26d-cad8-4808-8e30-54ca2c553773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Test Service Companion 102024/02/08</value>
      <webElementGuid>60847ba6-b61f-4a36-8d8b-1ccf70c87d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_grid--table_page_cell_base-2_0&quot;)</value>
      <webElementGuid>c05fc159-f536-4ab2-af06-2a5fca800fa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='data_grid--table_page_cell_base-2_0']</value>
      <webElementGuid>cd02196e-fc58-46eb-be15-d66601f62cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div/div/table/tbody/tr/td</value>
      <webElementGuid>3c07ce25-26e5-4d73-b3c5-60dc851cc81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>5f3dd957-00c8-4eff-8a74-9f5c2973ee40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'data_grid--table_page_cell_base-2_0' and (text() = 'Katalon Test Service Companion 102024/02/08' or . = 'Katalon Test Service Companion 102024/02/08')]</value>
      <webElementGuid>763fcc0b-5703-4abd-ac00-ada51e765abb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
