<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save Service Companion Button</name>
   <tag></tag>
   <elementGuidId>ab293df3-7ba0-424d-b35d-331ca2fa3357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-button--service_companion_edit_drawer_save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ui-button--service_companion_edit_drawer_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2dc96aaa-954d-43d3-bf89-34e17c130320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui button jss243 jss341 jss255</value>
      <webElementGuid>6ba1d243-5ad2-4f01-a5c1-5a0829e23e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-button--service_companion_edit_drawer_save</value>
      <webElementGuid>12835247-66c0-484d-86cf-59c5b33ab3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1519883d-1fc1-40e1-8464-9358bfa552fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-button--service_companion_edit_drawer_save&quot;)</value>
      <webElementGuid>44b38387-f8c8-4be1-a297-dcb17bdb2482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ui-button--service_companion_edit_drawer_save']</value>
      <webElementGuid>51248ef0-e9b1-427f-aba3-bea8674561d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div[2]/button</value>
      <webElementGuid>343db51e-9aa9-43a6-bc0d-39abda9b55bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ui-button--service_companion_edit_drawer_save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>392b412f-2f08-4b76-97ac-14c46087416c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
