<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Publish</name>
   <tag></tag>
   <elementGuidId>edbd1711-c630-47e6-b540-69e9c0ba7b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='connection_forms--details--publish_unpublish_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection_forms--details--publish_unpublish_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c954c507-bb3f-478e-8ef2-125cd9926d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui a jss360 jss273</value>
      <webElementGuid>a2e5908d-d539-453e-a8c1-b30e88cb8c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_forms--details--publish_unpublish_link</value>
      <webElementGuid>14bee21a-3e4a-48a6-8e6a-edcef52dac0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bde4fb56-1cac-40de-b1bc-bf4c34e39101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>07b3b537-b558-48bb-aa45-2ecad41ae64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publish</value>
      <webElementGuid>67d401b9-560c-4d35-9d36-6c08fc86045c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_forms--details--publish_unpublish_link&quot;)</value>
      <webElementGuid>2c08c2f0-7739-4971-8ba5-d271dec5d91e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='connection_forms--details--publish_unpublish_link']</value>
      <webElementGuid>ec88b306-b43c-4234-bd9d-4883109169f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div[2]/div/div/div/div/div[2]/div/div[7]/div/div/ul/li/div[2]/div/span</value>
      <webElementGuid>935e622d-5596-4a26-a30e-deab28723963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>025a23ab-e5a6-4215-8db1-ca18bd9d9479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'connection_forms--details--publish_unpublish_link' and (text() = 'Publish' or . = 'Publish')]</value>
      <webElementGuid>d5d153fc-1174-4448-a70c-b532d1648b6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
