<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First Name Field</name>
   <tag></tag>
   <elementGuidId>7c02a705-5dfb-46f3-819f-8e77bfaf8dc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#person_search_form--firstname_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'person_search_form--firstname_input' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32e2a6a5-88c1-4a89-8630-4f95b9864c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>person_search_form--firstname_input</value>
      <webElementGuid>8e44ebbb-91bd-4589-b738-feea6e6fadd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddb95f2d-640c-4974-81c1-680f37791bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;person_search_form--firstname_input&quot;)</value>
      <webElementGuid>23180a99-7d4a-4b8e-bcc8-7895063b0e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='person_search_form--firstname_input']</value>
      <webElementGuid>b68bb6a4-5158-4669-aa82-fadba4dea6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='person_search_form']/div/div/div/div/input</value>
      <webElementGuid>684993fd-cb99-4c3f-9450-139264479e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::input[1]</value>
      <webElementGuid>d0b0abbd-2fff-4454-a0cc-e7c9ce6ac15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Record'])[1]/following::input[1]</value>
      <webElementGuid>09643ca8-22d1-4a92-ada0-f933582034e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::input[1]</value>
      <webElementGuid>2326eb75-3569-4722-b4b3-51bc0bf04474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nick Name'])[1]/preceding::input[2]</value>
      <webElementGuid>b4c9aa1f-421a-4b25-b0c0-ee4acb60c271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/input</value>
      <webElementGuid>c4448428-df4f-49a8-8b15-2ab53cfa74ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'person_search_form--firstname_input' and @type = 'text']</value>
      <webElementGuid>a6a27dfa-a2bc-4553-b727-119c7fb88347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
