<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Actions Dropdown Settings</name>
   <tag></tag>
   <elementGuidId>525051e2-f2db-4a24-ad29-1a0130fe151f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Actions']/ancestor::div[contains(@class,'dropdown-button')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dropdown-selection-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>070d5ba7-7e59-42ea-ae70-a9903cb46920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-selection-value</value>
      <webElementGuid>e9c7ab11-6303-48d4-8a6d-7c12ff28c2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>279ec84f-caa8-4a85-80af-9dc0afc40a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss3479 jss3482 settings page-has_action_bar&quot;]/header[@class=&quot;ui page--action_bar action_bar&quot;]/div[1]/div[@class=&quot;cmui grid jss7 action_bar--grid jss13 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 action_bar--grid_column&quot;]/div[@class=&quot;btn-confirmation-container&quot;]/div[@class=&quot;ui dropdown btn-confirmation-child dropdown-button dropdown-color-primary dropdown-menu-theme-dark&quot;]/span[@class=&quot;dropdown-selection-value&quot;]</value>
      <webElementGuid>4edbd695-ef9e-4ca4-b2b1-5cfdbd2ec1f4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
