<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status Radio Button</name>
   <tag></tag>
   <elementGuidId>cfb7486b-e324-4978-95b6-eb96bb727fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.label.jss332 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::label[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Active&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5504608-6de9-4943-96bd-0d7bb49000be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>77f1e5c4-6544-4de6-8dd7-7783df81968d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;communication--filters_rail&quot;)/div[@class=&quot;ui rail jss304 jss292 jss298 jss299 jss293 jss302&quot;]/div[1]/div[1]/div[@class=&quot;jss301&quot;]/div[@class=&quot;cmui grid--column jss45&quot;]/div[@class=&quot;jss387&quot;]/div[@class=&quot;ui radio jss334 jss387&quot;]/label[@class=&quot;label jss332&quot;]/span[1]</value>
      <webElementGuid>42e4871c-877f-4ca6-bc67-4d4389aa707e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='communication--filters_rail']/div/div/div/div/div/div[2]/div/label/span</value>
      <webElementGuid>4eab3fe2-4004-479b-9358-accb98631f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::span[1]</value>
      <webElementGuid>a29dff5d-79b4-4824-b3ca-78f9b42107f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anaheim'])[2]/following::span[2]</value>
      <webElementGuid>b8334974-3610-42fe-93c4-d22d30d1dc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::span[1]</value>
      <webElementGuid>30d18050-2eaa-4c43-acd0-79ebb3944380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/preceding::span[2]</value>
      <webElementGuid>9e33eeb2-1dd5-41a9-b893-eed495cb153f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active']/parent::*</value>
      <webElementGuid>e16ca583-70ec-416e-9b8f-8b3ccb9a05cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>73c36fe7-b695-4b92-a66c-c343ded7df2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>721c2316-2620-43f9-b84e-1f67959f7d73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
