<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form_entry_editor--question_22944</name>
   <tag></tag>
   <elementGuidId>1a9e30dd-d722-4585-9fa7-f4140f3c6bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_entry_editor--question_22944']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_entry_editor--question_22944</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c45eeb27-254d-4a3e-96e4-fe34d6b82440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_entry_editor--question_22944</value>
      <webElementGuid>0acaa40a-7768-481a-9b5b-757a06c19765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PHT</value>
      <webElementGuid>2768bf37-f75b-48f2-8e94-a9c5fd0bd187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e674b966-daea-4816-9b45-130c0517c0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41073c0c-92dd-4069-8391-b0d23d114bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_entry_editor--question_22944&quot;)</value>
      <webElementGuid>c735434b-2951-4d6a-9e11-9674b78eb623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_entry_editor--question_22944']</value>
      <webElementGuid>8f984bc3-ba81-454d-8f39-d4fc863f46bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div[2]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>28b3158b-8aa0-4907-9e8a-13bd8222a5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>bfc7ff3b-348d-483f-8f7c-c43b9a534c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_entry_editor--question_22944' and @placeholder = 'PHT' and @type = 'text']</value>
      <webElementGuid>e3cbeb1a-d8c0-410c-a062-754e39e77b9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
