<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3</name>
   <tag></tag>
   <elementGuidId>3635ca60-0a89-4fdf-9f76-c9c5c5bba82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui.date-picker-day.date-picker-day-03.date-picker-day-today > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c4de3c9-046e-46be-a25c-0cd7c131826c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>14a3269e-3b01-46d4-adaa-962e600513e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hc-ui safari&quot;]/body[1]/div[@class=&quot;date-picker-tether-element date-picker-tether-abutted date-picker-tether-abutted-left date-picker-tether-element-attached-top date-picker-tether-element-attached-left date-picker-tether-target-attached-bottom date-picker-tether-target-attached-left date-picker-tether-enabled&quot;]/div[1]/div[@class=&quot;ui date-picker-calendar date-picker-calendar-mode-input date-picker-calendar-single-date&quot;]/div[@class=&quot;date-picker-month-container&quot;]/div[@class=&quot;ui date-picker-month&quot;]/div[@class=&quot;ui date-picker-week&quot;]/div[@class=&quot;ui date-picker-day date-picker-day-03 date-picker-day-today&quot;]/span[1]</value>
      <webElementGuid>fe112594-2d98-45eb-b290-45cbcd8808a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[9]</value>
      <webElementGuid>84490321-078c-41e1-a0b4-c2aba4425885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[9]</value>
      <webElementGuid>1277ef6b-0013-4f20-816f-0c183886f5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>a05e30c0-cd6e-4fab-ad9d-c9d6dd59effe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/span</value>
      <webElementGuid>46469827-3ecd-41ce-8b70-1a942b323d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '3' or . = '3')]</value>
      <webElementGuid>22bfe8b9-1de9-4aca-b60b-d631a001d38d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
