<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Basic Follow Up Push Notification</name>
   <tag></tag>
   <elementGuidId>e9456485-8b6c-460f-99bc-c5c893167a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Select-option.is-focused.is-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Basic Follow Up Push Notification' or . = 'Basic Follow Up Push Notification')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox >> internal:role=option[name=&quot;Basic Follow Up Push Notification&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c0938e2-6f6f-4c91-b001-2689c107f163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0ff95ef-ed04-443c-b73f-7c728485e42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-option is-focused is-selected</value>
      <webElementGuid>b7bf0ecc-8453-4500-8af6-9e765645d56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9160846f-baf5-4ba4-9c1f-d6e4676d8eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f38e5e64-ff4f-4e08-889b-129b9ba570bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basic Follow Up Push Notification</value>
      <webElementGuid>87ee2b3d-30f3-4bed-bb81-ea46c88da44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_action_form&quot;)/div[@class=&quot;cmui grid--column jss45&quot;]/div[@id=&quot;task_action_form--task_category_select&quot;]/div[@class=&quot;Select has-value is-focused is-open Select--single&quot;]/div[@class=&quot;Select-menu-outer&quot;]/div[@id=&quot;react-select-9--list&quot;]/div[1]/div[@class=&quot;select-menu-scrollbar&quot;]/div[1]/div[@class=&quot;Select-option is-focused is-selected&quot;]</value>
      <webElementGuid>2692eba7-cf4b-475c-940e-ce3d0f20c3d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='react-select-9--list']/div/div/div/div[2])[2]</value>
      <webElementGuid>40927285-f0d1-4f6c-88b6-489640b9f541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[2]/following::div[1]</value>
      <webElementGuid>abc294a3-30eb-4922-a492-3f84155a2b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Follow Up Push Notification'])[2]/following::div[10]</value>
      <webElementGuid>b86e0498-86ed-471f-8e3a-cc739e58c2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detailed Follow Up Push Notification'])[2]/preceding::div[1]</value>
      <webElementGuid>682b9afd-2d7d-4fc4-a5a2-9bf80dbdfc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important Follow Up Push Notification'])[2]/preceding::div[2]</value>
      <webElementGuid>444e3a73-14fa-41d7-9b97-d128b0a5456a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div/div/div/div[2]</value>
      <webElementGuid>f4954e43-c432-46a8-bd25-c2c05c1272c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Basic Follow Up Push Notification' or . = 'Basic Follow Up Push Notification')]</value>
      <webElementGuid>3014b468-0573-46ba-a53c-1bbb9f9d31fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
