<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Volunteer Button</name>
   <tag></tag>
   <elementGuidId>fc5b7a7a-f82d-452e-9920-b27745d216b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serving_opportunities--dropdown_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='serving_opportunities--dropdown_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8d6ba63-3060-482a-8769-7398320ac7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c289b342-389f-4994-995b-62f42f0df4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui button jss207 jss2027 jss205 button_dropdown jss215 jss217 jss206</value>
      <webElementGuid>214498ac-312c-42eb-9269-cf5516d219c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serving_opportunities--dropdown_button</value>
      <webElementGuid>bd7c4eb8-f3aa-4db4-a2b9-faabb81eccb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>636a48f6-3d11-476a-8275-696e0777fe1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>plusAdd VolunteerTo This OccurrenceTo All Occurrences</value>
      <webElementGuid>1b21728a-ef68-4e35-a84f-53e3c187847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serving_opportunities--dropdown_button&quot;)</value>
      <webElementGuid>14f44e69-9c96-4cf7-90fb-79c36338caf8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
