<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done_1</name>
   <tag></tag>
   <elementGuidId>6aff70a9-7b28-4d89-82fb-c2953eeb1533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='new_serving_ops_volunteer_req--btn_done']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new_serving_ops_volunteer_req--btn_done</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73947cc6-c7b2-4c83-b4df-b510efa06f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui button jss243 jss1138 jss253</value>
      <webElementGuid>b0f808c3-0006-4f33-8b79-a785e7884afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_serving_ops_volunteer_req--btn_done</value>
      <webElementGuid>7e39b0b7-eafd-49a6-b679-5a2f62e575f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>c8ae6d84-3778-403a-8448-11180fb82413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_serving_ops_volunteer_req--btn_done&quot;)</value>
      <webElementGuid>49615114-2867-41b2-8e82-f6f1906dde7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='new_serving_ops_volunteer_req--btn_done']</value>
      <webElementGuid>e3980541-0fe3-4513-96a4-9956a0e53f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/button[2]</value>
      <webElementGuid>44dc98d5-6ae7-49ea-a4e2-889a0d24e6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'new_serving_ops_volunteer_req--btn_done' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>482e9e5f-789d-4333-8d4f-a8c1a9688736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
