<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nextchevron-wh-right</name>
   <tag></tag>
   <elementGuidId>b87670e7-5da0-4a18-8690-f451744973c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='new_serving_opportunity_when_and_where--action_bar_next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new_serving_opportunity_when_and_where--action_bar_next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c3db49b-5afe-4d72-adbc-db5f7e43d95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui button jss243 jss1054 jss253</value>
      <webElementGuid>26a34e03-1466-4916-81b6-cb8eadd8dac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_serving_opportunity_when_and_where--action_bar_next</value>
      <webElementGuid>95a57898-ba3d-403f-a228-5e32c46b8ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nextchevron-wh-right</value>
      <webElementGuid>b2f89797-f16d-44c7-bb56-f9e02cfea221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_serving_opportunity_when_and_where--action_bar_next&quot;)</value>
      <webElementGuid>507187f3-dbb8-447c-87a3-98203e30ca41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='new_serving_opportunity_when_and_where--action_bar_next']</value>
      <webElementGuid>6046929d-cbca-45e0-bbce-eb48ad70537c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/button[2]</value>
      <webElementGuid>278c6916-fb56-4819-b91d-96f21de0456e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'new_serving_opportunity_when_and_where--action_bar_next' and (text() = 'Nextchevron-wh-right' or . = 'Nextchevron-wh-right')]</value>
      <webElementGuid>9dab36dc-d228-456c-83d8-bef1c4712410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
