<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nextchevron-wl-right</name>
   <tag></tag>
   <elementGuidId>5b80a965-dd84-4c7d-a874-36c65cd2f5a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ui-button--next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-button--next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa13f446-1174-41c8-bf05-d8eb7334875b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui button jss243 jss1005 jss253</value>
      <webElementGuid>38f6afae-239a-49e1-9252-987eb13c46c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-button--next</value>
      <webElementGuid>c428b952-3e42-4274-96fd-22361ae9b241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nextchevron-wl-right</value>
      <webElementGuid>55e39194-612d-46c0-bf89-bf1a169ca7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-button--next&quot;)</value>
      <webElementGuid>09470e82-f7b4-4fd2-8c52-c7c96ab3fa54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ui-button--next']</value>
      <webElementGuid>a54faed0-e87a-4ad7-aa19-adea1a5c68ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/header/div/button</value>
      <webElementGuid>5ca0db4a-5b4b-4c3c-96d8-802560057ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ui-button--next' and (text() = 'Nextchevron-wl-right' or . = 'Nextchevron-wl-right')]</value>
      <webElementGuid>197a5c6d-ee6b-4859-85a4-2cfd77f716f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
