<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Volunteers010</name>
   <tag></tag>
   <elementGuidId>98b178bc-8757-4c6e-a426-6b44543c730b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d0170df5-bd55-4b09-833d-79e34df21bc2']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cmui.grid.jss7.jss1820.jss1578.jss13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>466d8798-d62e-4f72-a4bb-03e3fb42715c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui grid jss7 jss1820 jss1578 jss13</value>
      <webElementGuid>5bee7bf8-fd08-471b-ae3c-1375a4d29e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>serving_opportunities--day_volunteer_count</value>
      <webElementGuid>e9fe0589-4fc2-480f-800a-30057c706eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volunteers0/10</value>
      <webElementGuid>656c191b-4180-4252-ae56-30a8ccbc6895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d0170df5-bd55-4b09-833d-79e34df21bc2&quot;)/div[@class=&quot;jss1567&quot;]/div[@class=&quot;jss1565&quot;]/div[@class=&quot;cmui grid jss7 jss1820 jss1578 jss13&quot;]</value>
      <webElementGuid>b3643ad0-eada-4d4d-95af-727f6cbb51ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d0170df5-bd55-4b09-833d-79e34df21bc2']/div/div[2]/div</value>
      <webElementGuid>71ee76c2-df6b-4858-878e-b209c4e0ac67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/div[2]/div</value>
      <webElementGuid>db5fcacd-e220-403d-ad62-91d78a70272e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Volunteers0/10' or . = 'Volunteers0/10')]</value>
      <webElementGuid>f818e626-6195-4dce-bc21-9b03bd60984e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
