<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_To This Occurrence</name>
   <tag></tag>
   <elementGuidId>e9f7dbe6-670f-400c-beee-f13a13588f7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='serving_opportunities--add_to_this_occurrence']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serving_opportunities--add_to_this_occurrence > div.dropdown_menu--option_inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cccea43f-2363-425e-a654-a04feb8a1a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_menu--option_inner</value>
      <webElementGuid>8ca9fbd0-b623-4a29-9704-0a236afeaf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>To This Occurrence</value>
      <webElementGuid>c5918a3b-601a-4c21-9682-e366cd615b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serving_opportunities--add_to_this_occurrence&quot;)/div[@class=&quot;dropdown_menu--option_inner&quot;]</value>
      <webElementGuid>ba138123-0e09-4790-8144-c8ffcaf9d6a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serving_opportunities--add_to_this_occurrence']/div</value>
      <webElementGuid>bf853caf-e2c9-46b8-8911-7d701cf063f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button/span/div[2]/div/div</value>
      <webElementGuid>6066094a-43a9-4063-a1db-75ab9cc68b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'To This Occurrence' or . = 'To This Occurrence')]</value>
      <webElementGuid>44ee2ca2-3a04-443a-952c-d4674731635f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
