<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select-value_1</name>
   <tag></tag>
   <elementGuidId>2a17bcb8-487b-4ca2-bf5a-eda8b8d5505e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-4--value']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-4--value > div.Select-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ade7a23-dd15-4225-984c-d8b579c0665f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-value</value>
      <webElementGuid>63766f57-2620-4057-9d17-e88d2e552047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-4--value&quot;)/div[@class=&quot;Select-value&quot;]</value>
      <webElementGuid>83b342fc-74a6-4c68-b15c-f5d2f0587ffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-4--value']/div</value>
      <webElementGuid>f779bcfc-34ea-4b06-878f-e3db064dcc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>bb8bc433-8765-4b67-a864-374615cb790f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
