<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Volunteers110</name>
   <tag></tag>
   <elementGuidId>be4c3a79-d6bb-49d5-9044-819328f47361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='9c9472bb-fc18-49fe-9d55-ee28a1349baa']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cmui.grid.jss7.jss3110.jss2825.jss13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa0afb3c-08c1-46fa-9047-a5d3b10d1fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui grid jss7 jss3110 jss2825 jss13</value>
      <webElementGuid>62ffb848-1c3e-478d-a433-7728ea6fd767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>serving_opportunities--day_volunteer_count</value>
      <webElementGuid>6a533045-643a-4443-8691-05d2147dfdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volunteers1/10</value>
      <webElementGuid>4c32664a-c568-48de-863f-cd6f1cbcc9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9c9472bb-fc18-49fe-9d55-ee28a1349baa&quot;)/div[@class=&quot;jss2814&quot;]/div[@class=&quot;jss2812&quot;]/div[@class=&quot;cmui grid jss7 jss3110 jss2825 jss13&quot;]</value>
      <webElementGuid>69eb5a3e-0ff0-4fb1-9db9-3bcddb2ad9a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9c9472bb-fc18-49fe-9d55-ee28a1349baa']/div/div[2]/div</value>
      <webElementGuid>98c066a6-5930-4111-9758-547b0c70a5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/div[2]/div</value>
      <webElementGuid>1059f1e7-16be-4939-89ea-aea23c13621b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Volunteers1/10' or . = 'Volunteers1/10')]</value>
      <webElementGuid>be85ba5f-9361-4412-b59b-7acd5664cc10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
