<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Remove From This Occurrence</name>
   <tag></tag>
   <elementGuidId>c555cdf5-c8d5-4ae6-bada-80ccbb333849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Remove From This Occurrence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serving_opportunities--actions_remove_from_all > div.dropdown_menu--option_inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96a6cab9-94d1-4982-beb7-ccc55290a377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_menu--option_inner</value>
      <webElementGuid>246ff134-9460-49a9-a610-cc12dbc29080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove From All Occurrences</value>
      <webElementGuid>18ab0dd9-ca1a-46b2-853b-bc788bfdaa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serving_opportunities--actions_remove_from_all&quot;)/div[@class=&quot;dropdown_menu--option_inner&quot;]</value>
      <webElementGuid>8dbe7ad0-4901-4d59-8099-98ee01d77807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serving_opportunities--actions_remove_from_all']/div</value>
      <webElementGuid>c4b1ff61-5717-462e-8741-dd6377cbb1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>0dc68ef8-668d-4150-8f6a-e1c31abcf1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Remove From All Occurrences' or . = 'Remove From All Occurrences')]</value>
      <webElementGuid>1fd3d341-103b-4ce2-a0a6-be4f2af12031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
