<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputschedule_capacity_drawer--input</name>
   <tag></tag>
   <elementGuidId>0fa0f56b-41f7-4050-b5bd-a07ce09f2f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='schedule_capacity_drawer--input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedule_capacity_drawer--input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5d07628-4043-4da2-851e-9f2487e717ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedule_capacity_drawer--input</value>
      <webElementGuid>08fe1bd1-8b69-4b9c-a218-9b78e8b813de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>56f3bcb8-b2fb-47c4-bb80-694f9ccd8f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7788a4c4-9055-4544-a715-35848d28e4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e0e42f36-6bf6-46d4-9f93-141f912230d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule_capacity_drawer--input&quot;)</value>
      <webElementGuid>8a187303-0cdf-47a7-a669-4d65859357b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='schedule_capacity_drawer--input']</value>
      <webElementGuid>87bb53d9-f66d-4944-90d3-2fb7bd0c23e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5da7dc57-4e1d-4b9d-8700-a148c1b4d308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'schedule_capacity_drawer--input' and @type = 'number']</value>
      <webElementGuid>60b371f4-fc3c-4556-8f89-d2a166566482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
