<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputcustom_question--props_placeholder_input--1</name>
   <tag></tag>
   <elementGuidId>01ae15c2-19d8-45e8-9c83-fecb53bf5b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom_question--props_placeholder_input--1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#custom_question--props_placeholder_input--1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c964f512-a270-4c6f-a598-f810dbe7ddde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom_question--props_placeholder_input--1</value>
      <webElementGuid>146a7e51-c7f3-4736-abb1-ae890713ec9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8701d8db-5ed2-4165-bf46-47b0b5d1f805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_question--props_placeholder_input--1&quot;)</value>
      <webElementGuid>af189535-fc27-472c-a249-3cec50581dd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom_question--props_placeholder_input--1']</value>
      <webElementGuid>d9f4e672-0f0d-4d6b-8f2b-c6bdd26d50a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>12495d07-9608-4dce-a6b3-c335273544c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'custom_question--props_placeholder_input--1' and @type = 'text']</value>
      <webElementGuid>0fc4047d-8338-45a6-b809-0987cb3efd6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
