<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Katalon Test SOWednesday, January 24, 20_6553a1</name>
   <tag></tag>
   <elementGuidId>8e6494bc-cc3e-4357-8a2f-aac229061745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='serving_opportunities--list_item-9279']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serving_opportunities--list_item-9279</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cba72200-3ba6-432b-823b-f0887a598b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItem-root jss3196 MuiListItem-gutters</value>
      <webElementGuid>1793edc9-1335-4fa4-9612-9870ef001eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serving_opportunities--list_item-9279</value>
      <webElementGuid>4a2087f1-0aa6-40a1-843e-052904c86556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>serving_opportunities--list_item</value>
      <webElementGuid>9f3f0ce9-2706-4024-9a8e-4e3ba692ae63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Test SOWednesday, January 24, 2024 | 9:00 AM - 10:00 AM PSTVolunteers1/10</value>
      <webElementGuid>4e5de782-d2a6-4327-af83-9b3cfe7127a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serving_opportunities--list_item-9279&quot;)</value>
      <webElementGuid>e7aa171d-0dbc-41ea-b393-fd2c42c13f30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='serving_opportunities--list_item-9279']</value>
      <webElementGuid>c2900cce-4823-470c-aa2b-2158098b4e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/ul/li</value>
      <webElementGuid>2506d1da-98fb-4ff5-a95a-c0017153f234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'serving_opportunities--list_item-9279' and (text() = 'Katalon Test SOWednesday, January 24, 2024 | 9:00 AM - 10:00 AM PSTVolunteers1/10' or . = 'Katalon Test SOWednesday, January 24, 2024 | 9:00 AM - 10:00 AM PSTVolunteers1/10')]</value>
      <webElementGuid>119d60fd-e60f-4fce-bf6b-0c0fb1692ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
