<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_ClosefiltersSearchEmailText Messagebel_3fbb26</name>
   <tag></tag>
   <elementGuidId>c9b95fe8-32b8-4974-87ef-5960147fa18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/main</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>main.ui.page.jss3202.jss3205.page-has_action_bar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>40692c8f-ca2b-4b26-9927-43cb8a80b60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui page jss3202 jss3205 page-has_action_bar</value>
      <webElementGuid>5db6fc74-44ef-45fa-8395-6493ff2aa106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui-page</value>
      <webElementGuid>c581c0cc-32b9-4230-9a23-32a1d0a05cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ClosefiltersSearchEmailText MessagebellEmail ReminderSMS ReminderCheck-Inchevron-downActionsAdd Volunteer To This OccurrenceAdd Volunteer To All OccurrencesSend EmailSend Text MessageRemindersCheck-InExport Occurrence Roster(CSV)Export Occurrence Roster(XLSX)Edit Volunteer CapacityRemove From ?YesNoplusAdd VolunteerTo This OccurrenceTo All Occurrenceschevron-leftJanuary 2024chevron-rightSuMoTuWeThFrSa311234567891011121314151617181920212223242526272829303112345678910SortFirst Name (Ascending)First Name (Descending)Last Name (Ascending)Last Name (Descending)Date Added (Ascending)Date Added (Descending)Last Name (Ascending)SelectMinistry MembershipMemberscheckNon MemberscheckServed StatusAnyServedNot ServedCheck-In StatusAnyChecked InNot Checked InGroupsExpandRolesExpandHome CampusExpandAnaheimcheckAutomatedCampuscheckBerlincheckBreacheckBryant's Test CampuscheckBuena ParkcheckBuenos AirescheckCampusToCreateEvent01checkCampusToCreateEvent02checkCampusToUpdateEvent01checkCoronacheckEagancheckEastvalecheckExtensionscheckGarrett's Test CampuscheckGranadacheckHong KongcheckHuntington BeachcheckIrvine NorthcheckIrvine SouthcheckLaguna WoodscheckLake ForestcheckLos AngelescheckNew CampuscheckNewport MesacheckNorthridge HGcheckOnline CommunitycheckPrescottcheckQA ME Auto Test CampuscheckQA ME Manual Test CampuscheckQA Test Campus 1.23.0checkRancho CapistranocheckSA Nepal Test1checkSA3checkST Campus TestcheckSacramentocheckSaddleback en EspañolcheckSan Antonio - Test1checkSan Antonio - Test2checkSan ClementecheckSan DiegocheckSanta RosacheckSouth BaycheckStockholm CampuscheckTemeculacheckVancouvercheckWhittiercheckOtherMissing RequirementscheckWednesday, January 24th, 202409:00 am - 10:00 amCreated with Highcharts 6.2.0Capacity10Volunteers1checkPicPerson DetailssplitterServedCheck-In StatusMilestonesGroupsRolesDate AddedMinistryMissing ReqcheckGCGarrett CloverMale|Lake ForestNot ServedNot Checked InHas not accepted ChristNot BaptizedNot active in Small GroupNot active in Missions01/24/2024</value>
      <webElementGuid>bc9b0543-d854-449d-8720-53bc92e46119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss3202 jss3205 page-has_action_bar&quot;]</value>
      <webElementGuid>a9de7da5-af76-4da5-bf95-9f91491496e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main</value>
      <webElementGuid>673c10ad-a6e3-4b29-b53e-63e697476f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main</value>
      <webElementGuid>421681b9-a2b0-44b4-9305-22f03d7b0997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//main[(text() = concat(&quot;ClosefiltersSearchEmailText MessagebellEmail ReminderSMS ReminderCheck-Inchevron-downActionsAdd Volunteer To This OccurrenceAdd Volunteer To All OccurrencesSend EmailSend Text MessageRemindersCheck-InExport Occurrence Roster(CSV)Export Occurrence Roster(XLSX)Edit Volunteer CapacityRemove From ?YesNoplusAdd VolunteerTo This OccurrenceTo All Occurrenceschevron-leftJanuary 2024chevron-rightSuMoTuWeThFrSa311234567891011121314151617181920212223242526272829303112345678910SortFirst Name (Ascending)First Name (Descending)Last Name (Ascending)Last Name (Descending)Date Added (Ascending)Date Added (Descending)Last Name (Ascending)SelectMinistry MembershipMemberscheckNon MemberscheckServed StatusAnyServedNot ServedCheck-In StatusAnyChecked InNot Checked InGroupsExpandRolesExpandHome CampusExpandAnaheimcheckAutomatedCampuscheckBerlincheckBreacheckBryant&quot; , &quot;'&quot; , &quot;s Test CampuscheckBuena ParkcheckBuenos AirescheckCampusToCreateEvent01checkCampusToCreateEvent02checkCampusToUpdateEvent01checkCoronacheckEagancheckEastvalecheckExtensionscheckGarrett&quot; , &quot;'&quot; , &quot;s Test CampuscheckGranadacheckHong KongcheckHuntington BeachcheckIrvine NorthcheckIrvine SouthcheckLaguna WoodscheckLake ForestcheckLos AngelescheckNew CampuscheckNewport MesacheckNorthridge HGcheckOnline CommunitycheckPrescottcheckQA ME Auto Test CampuscheckQA ME Manual Test CampuscheckQA Test Campus 1.23.0checkRancho CapistranocheckSA Nepal Test1checkSA3checkST Campus TestcheckSacramentocheckSaddleback en EspañolcheckSan Antonio - Test1checkSan Antonio - Test2checkSan ClementecheckSan DiegocheckSanta RosacheckSouth BaycheckStockholm CampuscheckTemeculacheckVancouvercheckWhittiercheckOtherMissing RequirementscheckWednesday, January 24th, 202409:00 am - 10:00 amCreated with Highcharts 6.2.0Capacity10Volunteers1checkPicPerson DetailssplitterServedCheck-In StatusMilestonesGroupsRolesDate AddedMinistryMissing ReqcheckGCGarrett CloverMale|Lake ForestNot ServedNot Checked InHas not accepted ChristNot BaptizedNot active in Small GroupNot active in Missions01/24/2024&quot;) or . = concat(&quot;ClosefiltersSearchEmailText MessagebellEmail ReminderSMS ReminderCheck-Inchevron-downActionsAdd Volunteer To This OccurrenceAdd Volunteer To All OccurrencesSend EmailSend Text MessageRemindersCheck-InExport Occurrence Roster(CSV)Export Occurrence Roster(XLSX)Edit Volunteer CapacityRemove From ?YesNoplusAdd VolunteerTo This OccurrenceTo All Occurrenceschevron-leftJanuary 2024chevron-rightSuMoTuWeThFrSa311234567891011121314151617181920212223242526272829303112345678910SortFirst Name (Ascending)First Name (Descending)Last Name (Ascending)Last Name (Descending)Date Added (Ascending)Date Added (Descending)Last Name (Ascending)SelectMinistry MembershipMemberscheckNon MemberscheckServed StatusAnyServedNot ServedCheck-In StatusAnyChecked InNot Checked InGroupsExpandRolesExpandHome CampusExpandAnaheimcheckAutomatedCampuscheckBerlincheckBreacheckBryant&quot; , &quot;'&quot; , &quot;s Test CampuscheckBuena ParkcheckBuenos AirescheckCampusToCreateEvent01checkCampusToCreateEvent02checkCampusToUpdateEvent01checkCoronacheckEagancheckEastvalecheckExtensionscheckGarrett&quot; , &quot;'&quot; , &quot;s Test CampuscheckGranadacheckHong KongcheckHuntington BeachcheckIrvine NorthcheckIrvine SouthcheckLaguna WoodscheckLake ForestcheckLos AngelescheckNew CampuscheckNewport MesacheckNorthridge HGcheckOnline CommunitycheckPrescottcheckQA ME Auto Test CampuscheckQA ME Manual Test CampuscheckQA Test Campus 1.23.0checkRancho CapistranocheckSA Nepal Test1checkSA3checkST Campus TestcheckSacramentocheckSaddleback en EspañolcheckSan Antonio - Test1checkSan Antonio - Test2checkSan ClementecheckSan DiegocheckSanta RosacheckSouth BaycheckStockholm CampuscheckTemeculacheckVancouvercheckWhittiercheckOtherMissing RequirementscheckWednesday, January 24th, 202409:00 am - 10:00 amCreated with Highcharts 6.2.0Capacity10Volunteers1checkPicPerson DetailssplitterServedCheck-In StatusMilestonesGroupsRolesDate AddedMinistryMissing ReqcheckGCGarrett CloverMale|Lake ForestNot ServedNot Checked InHas not accepted ChristNot BaptizedNot active in Small GroupNot active in Missions01/24/2024&quot;))]</value>
      <webElementGuid>560bc0e9-3c0b-4374-a940-e754381abe88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
