<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Members Tab</name>
   <tag></tag>
   <elementGuidId>4a93aa2f-14c2-44f6-892a-58343bfc905c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-navigation_tab--key-item-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-navigation_tab--key-item-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4af0cf75-8ee6-4c5c-b97e-617fdc341ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96a857fb-52fb-44f8-8e7b-4f323edbf3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss398 navigation_sectional_tabs--tab navigation_sectional_tabs--tab--first</value>
      <webElementGuid>272d53b4-ffaf-4728-913e-bd9a6a6b9efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-navigation_tab--key-item-0</value>
      <webElementGuid>a5395be1-59be-47e2-9a3b-95a3a53b3459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ed24bf9e-1fbd-4951-b0c3-428c60c469e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7c5ec459-9030-4255-a4a0-cf23a4710ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78e5fa14-417b-4602-9210-c3eeed79da4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Members</value>
      <webElementGuid>16f3a28e-9922-4497-8bf5-50772017590c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-navigation_tab--key-item-0&quot;)</value>
      <webElementGuid>bffdd2c2-d6a1-4e72-b57f-759953dbf388</webElementGuid>
   </webElementProperties>
</WebElementEntity>
