<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remove From This Occurence Confirmation Yes Button</name>
   <tag></tag>
   <elementGuidId>54d490d8-a920-411c-b831-8e90203a8946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui.prompt.jss1927.jss2191.prompt-show.prompt-inline > div.prompt-actions.jss1926 > div.prompt-yes-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='prompt-yes-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51e0e4e9-6060-4d09-8f7e-467274ee5f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prompt-yes-btn</value>
      <webElementGuid>a9337d80-513d-45bf-94df-6ec5f527e153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b461d652-a5e2-4753-8d80-2be4f837a7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>207e97f3-31cc-497c-820d-2d3fef422360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>de7e784a-8edf-4ae4-8a1f-1c4d8232dce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;people_search_drawer--results&quot;)/div[@class=&quot;jss2057 jss2052 cmui person_panel&quot;]/div[@class=&quot;jss2084 jss2050 jss2055 cmui person_panel--details jss2082&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[@class=&quot;jss2081&quot;]/div[@class=&quot;jss2079&quot;]/div[@class=&quot;ui prompt jss1927 jss2191 prompt-show prompt-inline&quot;]/div[@class=&quot;prompt-actions jss1926&quot;]/div[@class=&quot;prompt-yes-btn&quot;]</value>
      <webElementGuid>748a3b26-263a-4656-a4a7-a39bb3f2261c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
