<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save Button</name>
   <tag></tag>
   <elementGuidId>6d1bea4d-fb60-4ad1-9ba7-ae96c47c4ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new_serving_ops_drawer--btn_save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='new_serving_ops_drawer--btn_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4a86e35-fd6f-4e62-b945-adf9e62df0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui button jss243 jss998 jss255</value>
      <webElementGuid>10d5f3b5-47fe-4f24-9505-885b7cbadb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_serving_ops_drawer--btn_save</value>
      <webElementGuid>61a2bdfb-db4f-41fa-a110-d49602f2b8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>00675c5b-254a-4033-b78c-af0d31533ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_serving_ops_drawer--btn_save&quot;)</value>
      <webElementGuid>8163b2f7-4a1c-4190-a62a-3c4ac0373cee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='new_serving_ops_drawer--btn_save']</value>
      <webElementGuid>7ea6d2ea-fff5-4bdc-b1c8-79622e19c43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>f0cb27e7-f98b-49e9-bf91-53fdcf0abf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'new_serving_ops_drawer--btn_save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>e9580c5d-0323-4307-8f01-da125e109f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
