<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Short Description Text Field</name>
   <tag></tag>
   <elementGuidId>47424a72-8a94-4935-94f6-1320be3abc10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-input--so_short_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ui-input--so_short_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a95d3ad-cbee-4766-b147-db8e26f02a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-input--so_short_description</value>
      <webElementGuid>850af91c-9bc8-4716-bca1-8a276e35ceb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>b1e70195-972b-4487-9e15-2de56be52634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39a77cdb-c81e-46fb-afe2-ca423a29b18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-input--so_short_description&quot;)</value>
      <webElementGuid>91608184-ae58-4010-9d52-0d30aaf85627</webElementGuid>
   </webElementProperties>
</WebElementEntity>
