<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Person Search</name>
   <tag></tag>
   <elementGuidId>17ae3f44-dd5a-4382-9dd4-cbf03b2fbd81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sub_navigation_button--person_search']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub_navigation_button--person_search > span.sub-navigation-button-inner > span.copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>feaa51eb-b29b-4755-b054-fa01e96bc382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>copy</value>
      <webElementGuid>5632a79e-f00f-405f-aa4e-9d3056a89b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Person Search</value>
      <webElementGuid>c7ad341f-d872-4e67-8c76-d5c12bfe2ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub_navigation_button--person_search&quot;)/span[@class=&quot;sub-navigation-button-inner&quot;]/span[@class=&quot;copy&quot;]</value>
      <webElementGuid>58d10395-c1cd-4df6-a898-b8be6e858fb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='sub_navigation_button--person_search']/span/span</value>
      <webElementGuid>d74f3d30-b673-488a-a24b-ebeaf868538c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span/span</value>
      <webElementGuid>28edafd7-ea95-4138-b43f-d949961a5a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Person Search' or . = 'Person Search')]</value>
      <webElementGuid>a61ff311-90b5-468e-b78a-000ed6fa02af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
