<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes</name>
   <tag></tag>
   <elementGuidId>0fae686e-b875-4b7f-b33f-8b64d20d8def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/main/header/div/div/div/div/div[2]/div/a/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn-inner > span.copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ec025c69-b1a7-404f-a37f-c9055b338c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>copy</value>
      <webElementGuid>854e5c25-0a3b-4939-a8ba-bf6fa498e13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>4e46c8d8-74b0-41eb-bec9-8e8ed8373887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss3479 jss3482 settings page-has_action_bar&quot;]/header[@class=&quot;ui page--action_bar action_bar&quot;]/div[1]/div[@class=&quot;cmui grid jss7 action_bar--grid jss13 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 action_bar--grid_column&quot;]/div[@class=&quot;btn-confirmation-container is-active&quot;]/div[@class=&quot;btn-confirmation animate-from-right&quot;]/div[@class=&quot;btn-inner&quot;]/a[@class=&quot;btn btn-yes btn-primary btn-inline&quot;]/span[@class=&quot;btn-inner&quot;]/span[@class=&quot;copy&quot;]</value>
      <webElementGuid>94b8108e-ffa9-4a38-956b-b36360c86888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/header/div/div/div/div/div[2]/div/a/span/span</value>
      <webElementGuid>98a9ebe0-1d91-46e0-b425-8e7c6a0cccd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/span</value>
      <webElementGuid>eefd543d-43f2-4b1b-b838-8c1fd1d68ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>0c3e8e52-33b7-46c0-a175-65c0529106e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
