<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Actions</name>
   <tag></tag>
   <elementGuidId>525051e2-f2db-4a24-ad29-1a0130fe151f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/main/header/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dropdown-selection-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d97f15c-b684-49bd-8886-e2b1dac1fc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-selection-value</value>
      <webElementGuid>e74db2db-f102-41fd-9278-19851fd12da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>84dd5a2d-eb44-453c-b868-f82d864f0c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss3479 jss3482 settings page-has_action_bar&quot;]/header[@class=&quot;ui page--action_bar action_bar&quot;]/div[1]/div[@class=&quot;cmui grid jss7 action_bar--grid jss13 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 action_bar--grid_column&quot;]/div[@class=&quot;btn-confirmation-container&quot;]/div[@class=&quot;ui dropdown btn-confirmation-child dropdown-button dropdown-color-primary dropdown-menu-theme-dark&quot;]/span[@class=&quot;dropdown-selection-value&quot;]</value>
      <webElementGuid>c4919020-3139-49d2-a887-966adda739ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/header/div/div/div/div/div/span</value>
      <webElementGuid>be24d541-a0b6-4f04-adab-bd929384a126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div/div/div/span</value>
      <webElementGuid>3f8f181b-6125-4583-8acf-5865e0729393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>75c88c42-39bc-4520-83cc-d694fa2cfe34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
