<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Event SO Test Ministry</name>
   <tag></tag>
   <elementGuidId>82e76030-ec05-4f56-a32e-e12672e13ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ui-table_row--ministry_central_row_2206']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.table-cell.table-cell-font-size-small.table-cell-twelve.table-cell-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c77217a6-e6d2-4093-97a7-cfbd59417c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-cell table-cell-font-size-small table-cell-twelve table-cell-name</value>
      <webElementGuid>eeb2a00f-7de2-4317-9760-84505f9c6d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event SO Test Ministry</value>
      <webElementGuid>943af70b-b324-487c-ad3e-d715967e56fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-table_row--ministry_central_row_2206&quot;)/td[@class=&quot;table-cell table-cell-font-size-small table-cell-twelve table-cell-name&quot;]</value>
      <webElementGuid>023a49ad-4231-4892-8b83-28b8df1108ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ui-table_row--ministry_central_row_2206']/td[2]</value>
      <webElementGuid>c43706ee-c191-4441-9f41-7bb0ff93daf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>8b8cac55-a684-41ac-9d94-75df88a281aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Event SO Test Ministry' or . = 'Event SO Test Ministry')]</value>
      <webElementGuid>03efdf42-f5ec-4e22-b04e-9643695dc6d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
