<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_SO Created for Katalon Testing</name>
   <tag></tag>
   <elementGuidId>6ad1c321-279e-474a-97d5-abfd7d5fc03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ui-textarea--so_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-textarea--so_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fd646e75-69a1-4cb7-b337-e0f555d36e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-textarea--so_description</value>
      <webElementGuid>e7fbfc4f-0141-43b7-9c72-13474038b544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2048</value>
      <webElementGuid>75815f8e-ecf5-465b-be68-436e3f8a4ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SO Created for Katalon Testing</value>
      <webElementGuid>005d7112-c892-4b06-8306-52201c5708a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-textarea--so_description&quot;)</value>
      <webElementGuid>4e4b262d-7336-4621-80cd-cc08315f9bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ui-textarea--so_description']</value>
      <webElementGuid>eae3d6b2-fa05-4ac1-81f0-d845d17002f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dd6936ef-e88f-4f94-98a7-e902a4866249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ui-textarea--so_description' and (text() = 'SO Created for Katalon Testing' or . = 'SO Created for Katalon Testing')]</value>
      <webElementGuid>5f8bfe18-9872-418e-b2f8-6ef53a954c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
