<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use_icon-use-path</name>
   <tag></tag>
   <elementGuidId>1f8ec700-cf5f-45e0-b3ae-a654b6dede6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select_venue--select_venue_908 > label.checkbox-label > div.cmui.ui.icon.icon-check.icon-align-left.icon-color-primary.icon-compact.icon-inverse > svg > g > use.icon-use-path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>c9b8599c-4c09-47d2-b8c3-8cb36b4b5585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-use-path</value>
      <webElementGuid>9fb74a54-539e-42d7-a2e9-b48299a7e6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>#icon-svg-path-check-5130865680</value>
      <webElementGuid>329d218d-226e-4b57-938a-cc7d3e01e345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_serving_opportunity_when_and_where--where&quot;)/div[5]/table[@class=&quot;ui jss1000 table table-basic table-font-size-xsmall table-selectable&quot;]/tbody[@class=&quot;table-body&quot;]/tr[@id=&quot;select_venue--select_venue_908&quot;]/td[@class=&quot;table-cell&quot;]/div[@id=&quot;select_venue--select_venue_908&quot;]/label[@class=&quot;checkbox-label&quot;]/div[@class=&quot;cmui ui icon icon-check icon-align-left icon-color-primary icon-compact icon-inverse&quot;]/svg[1]/g[1]/use[@class=&quot;icon-use-path&quot;]</value>
      <webElementGuid>ec6e6707-39c4-4da9-8f20-0b89f6ed74a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
