<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Segment Status Radio Button</name>
   <tag></tag>
   <elementGuidId>d1e5290a-b7c0-4b3a-81a1-602bbec621cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#segment_primary_details_edit__save_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = '${Status}' or . = '${Status}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6712b0e2-757a-47ea-a5b0-ebc02657cfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>75a77302-e21e-4e0d-99d8-11474641c46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui button jss207 jss535 jss215 jss206</value>
      <webElementGuid>cec6600b-e4cb-4a21-acff-b4ab1e858c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segment_primary_details_edit__save_button</value>
      <webElementGuid>291dcf68-b64b-4869-a7da-cf54d3413cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46b63bae-daaf-4b36-a3ce-765b1dfe5db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>6223b9e2-0227-4e83-ae72-8473e0c101ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segment_primary_details_edit__save_button&quot;)</value>
      <webElementGuid>73a07f15-f03a-4340-a13d-350091e54c15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='segment_primary_details_edit__save_button']</value>
      <webElementGuid>cca6813a-3476-4983-a20a-41aecc48f166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>f11f510b-5770-4e36-ab35-17b8d173226d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Segment Info'])[1]/following::button[2]</value>
      <webElementGuid>8fcf356f-9f37-4ed5-b65c-61c92158d7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segment Info'])[1]/preceding::button[1]</value>
      <webElementGuid>0cffda07-4ce0-479d-9dbb-9bd16b19fc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div[2]/button</value>
      <webElementGuid>d0724fde-cab3-477c-a390-b63ba85a22d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'segment_primary_details_edit__save_button' and @type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>f13e1158-9d88-4d10-abc6-6f7a0543cc0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
