<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_OnOffcheck</name>
   <tag></tag>
   <elementGuidId>926a405f-230c-44f4-8256-9a93a678db78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#feature-27-toggle > label.checkbox-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feature-27-toggle']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#feature-27-toggle >> internal:text=&quot;OnOffcheck&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>af9ada09-8a79-45de-b33b-506903243681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-label</value>
      <webElementGuid>a39ce153-bade-48ab-a6f1-6030335c94db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OnOffcheck</value>
      <webElementGuid>4d99be56-0941-4cc1-987e-6c72516f7825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feature-27-toggle&quot;)/label[@class=&quot;checkbox-label&quot;]</value>
      <webElementGuid>968ba75c-11ea-484f-9dfb-d5212053ebdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feature-27-toggle']/label</value>
      <webElementGuid>4cb8f36a-1650-455f-b3cc-1f4f7da87797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Program Management'])[1]/following::label[1]</value>
      <webElementGuid>7c1615c7-a0db-414b-bdc0-6f1dd706af21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance back-office administrative functionality (APIs and UI)'])[1]/following::label[1]</value>
      <webElementGuid>1498b29d-6698-45a8-baec-2922fa720eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/label</value>
      <webElementGuid>21669ad8-c064-4b93-943a-27400b324d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'OnOffcheck' or . = 'OnOffcheck')]</value>
      <webElementGuid>8d46a5b9-f741-4bd2-9f75-8b049f594811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
