<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Digital Program Details Last Update Date</name>
   <tag></tag>
   <elementGuidId>f6102684-ec42-4a0d-a626-794905de0bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/main/div/div/div[2]/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>decfa84e-fde9-40fe-b741-9e5cc0debbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root jss1191 MuiTypography-h4</value>
      <webElementGuid>7cbdaa17-2d82-4e36-8e36-23c30ceb8566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>05/30/2024</value>
      <webElementGuid>c24bb136-1322-4e8e-ac83-e1a29fd3958a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss240 jss1194 jss1190 page-has_action_bar&quot;]/div[@class=&quot;cmui container jss248 ui page--container jss247&quot;]/div[@class=&quot;cmui grid jss7 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 jss1189 jss68 jss76&quot;]/div[@class=&quot;jss1188&quot;]/div[@class=&quot;MuiTypography-root jss1191 MuiTypography-h4&quot;]</value>
      <webElementGuid>449c11c7-9dcf-4b1a-8d1d-b27d726dae0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/div/div[2]/div[4]/div</value>
      <webElementGuid>10a0b3c5-d8a3-474f-9c58-d934542dea43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By'])[1]/following::div[2]</value>
      <webElementGuid>c426b5a1-4785-485b-b701-a5cc2c8f6614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Automation Default Member'])[1]/following::div[3]</value>
      <webElementGuid>576ab43e-031f-4179-90f9-b2481b5f5f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Update'])[1]/preceding::div[1]</value>
      <webElementGuid>717276c5-379d-492b-81f4-6d80eb1c943a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sreenivasulu Arveti'])[1]/preceding::div[2]</value>
      <webElementGuid>ac7a85c2-f4a8-43d4-81c5-2cb2fb556ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>6dd0ab46-8ec7-4ce9-8b98-fdb78d8aeb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '05/30/2024' or . = '05/30/2024')]</value>
      <webElementGuid>d5bde1d5-5bd8-4e09-865e-a99a06a7605a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
