<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Digital Program Speaker Dropdown button</name>
   <tag></tag>
   <elementGuidId>8b1598bd-252c-4a0f-9279-8e67748a1214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-58--value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-58--value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed38fbad-e9a0-4d69-bdc0-f6ade4c33102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-multi-value-wrapper</value>
      <webElementGuid>f3f7370b-24fc-4528-a4f5-a2229ec2b00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-58--value</value>
      <webElementGuid>ba46bc56-1728-43d1-b387-f5f76a9f697b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>× </value>
      <webElementGuid>c6f73865-34aa-4904-8882-3a1276f03fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-58--value&quot;)</value>
      <webElementGuid>fc7ea60c-0d57-4afc-afd4-497f8d469192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-58--value']</value>
      <webElementGuid>b45d36cf-fc05-4e15-8e5b-5f9ef28c9fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='digital_programs_add_drawer--speaker']/div/div[2]/div</value>
      <webElementGuid>df6b081e-6d38-4088-81c1-6d217c030354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Speaker'])[1]/following::div[6]</value>
      <webElementGuid>5c114066-86c3-4c44-84eb-2db974f842ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HC-QA Sreeni DP Speaker'])[1]/following::div[7]</value>
      <webElementGuid>b16d7b2c-7943-4232-8548-b6fe2c6405d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[15]</value>
      <webElementGuid>74ab0442-5b99-4c91-8614-5c8e00583f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div</value>
      <webElementGuid>4f9ba3cf-1e1e-491b-a38f-a08a44815569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-58--value' and (text() = '× ' or . = '× ')]</value>
      <webElementGuid>93ccbef9-b061-455d-b4bd-e267b43b6945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
