<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Digital Program Builder Template dropdown</name>
   <tag></tag>
   <elementGuidId>3147d73e-220b-44d4-b614-47c80e3acfca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Template' or . = 'Template')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Select-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5227b571-4a7e-4605-9c7e-6cbfa12f27ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-placeholder</value>
      <webElementGuid>d234ae90-f45f-4d7d-b80b-84bae08ae024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Template</value>
      <webElementGuid>017a325e-25d7-4c9a-b3d6-2afa066eee05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-6--value&quot;)/div[@class=&quot;Select-placeholder&quot;]</value>
      <webElementGuid>54e802f9-aeb1-4b5f-b977-6080307afea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-6--value']/div</value>
      <webElementGuid>073fddb7-cf6a-48aa-a01f-a74c4c6f6790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testing lower case'])[1]/following::div[7]</value>
      <webElementGuid>ebd7864d-31a5-432d-b25a-aec837381460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yorba Linda'])[1]/following::div[8]</value>
      <webElementGuid>c5f1ef0f-366c-49f7-b19c-07b9f11aaa9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Details'])[1]/preceding::div[5]</value>
      <webElementGuid>bec0bfa6-9efd-4589-bf8f-4fe1e9c81dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Builder'])[2]/preceding::div[7]</value>
      <webElementGuid>c259164b-ee2a-441c-b60b-098ea4811fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Template']/parent::*</value>
      <webElementGuid>74a75f64-507c-4841-b5c3-307c7d7ddc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>37b9baac-25ea-431f-b6a6-a1bb9e5be24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Template' or . = 'Template')]</value>
      <webElementGuid>a9701701-4684-46c3-adee-05b5c5afd985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
