<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cancel Event Button</name>
   <tag></tag>
   <elementGuidId>69e22d89-44bb-45fa-8748-6ff61a1c3a09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_details--actions_dropdown_2 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='event_details--actions_dropdown_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce4d1b35-a606-4f58-b34a-15f70d5387f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>4af64619-98fa-4027-acdb-86e3236fd66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event_details--actions_dropdown_2&quot;)/span[1]</value>
      <webElementGuid>40d61b03-aa8f-4fc1-8be3-bcc58f4fd95b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
