<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Overview Tab</name>
   <tag></tag>
   <elementGuidId>48a6f631-526f-4ab6-9d6c-b429f8febf97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiTypography-root.jss595.navigation_sectional_tabs--tab-label.MuiTypography-h5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-navigation_tab--key-item-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab81a077-f091-40a5-b88b-10dcae8b54ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root jss595 navigation_sectional_tabs--tab-label MuiTypography-h5</value>
      <webElementGuid>db5a6a12-f8c6-43cd-9ed4-ddeb499db680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>4cf307e6-5358-4922-b4be-d817cdb16820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-navigation_tab--key-item-0&quot;)/span[@class=&quot;MuiTypography-root jss595 navigation_sectional_tabs--tab-label MuiTypography-h5&quot;]</value>
      <webElementGuid>e93e6a7c-3ab9-4604-ae0a-868c672b7250</webElementGuid>
   </webElementProperties>
</WebElementEntity>
