<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Location Header Link</name>
   <tag></tag>
   <elementGuidId>e1e15d9f-eb42-42d2-8448-f75ff991c327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.footer-nav-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Locations')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a6e891a-004e-4fdc-92d1-51c25383d40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/locations/</value>
      <webElementGuid>6485b010-a9b8-423f-bd87-a481e71eae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-nav-page</value>
      <webElementGuid>c23b61a6-d3c1-40bb-9700-ac134360153d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Locations</value>
      <webElementGuid>b19cea5a-d34d-4f9d-9561-fb88e792dad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;header-desktop-menu desktop-center&quot;]/ul[1]/li[1]/a[@class=&quot;footer-nav-page&quot;]</value>
      <webElementGuid>dad3f720-2d6b-4423-9e0b-a1a521a02779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Locations')]</value>
      <webElementGuid>69a78f88-626e-49f9-8150-33bec1e926e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/locations/')]</value>
      <webElementGuid>4ba31c58-ee70-4e3b-b9d9-2a8701f06deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>442827e9-6c02-4b3e-a926-8a8f3a5f1d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/locations/' and (text() = 'Locations' or . = 'Locations')]</value>
      <webElementGuid>fbd0d52a-0b36-4bcc-892e-0480dd89b7b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
