<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__segment_create--segment_name</name>
   <tag></tag>
   <elementGuidId>318be495-037b-44a9-b9b8-8b61a445290d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#segment_create--segment_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='segment_create--segment_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afbe7d69-1f53-40d4-8ec4-af4a658d7fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>segment_create--input_segment_name</value>
      <webElementGuid>8cab4c3d-f408-48bc-91f8-0029c6223634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segment_create--segment_name</value>
      <webElementGuid>051efb73-0996-467a-a3d2-f8f24cb5cdbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>bb1b55d6-5735-4824-94fe-7a9e94ae1b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61aa784f-8bbc-4b70-8582-58af6135e8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segment_create--segment_name&quot;)</value>
      <webElementGuid>23b89104-b973-40d6-9e91-7c5231d46be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='segment_create--segment_name']</value>
      <webElementGuid>06f400a5-49db-47cb-b87c-a481767e0789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div/input</value>
      <webElementGuid>90992f72-f965-457c-9c8f-975fa5819caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'segment_create--segment_name' and @type = 'text']</value>
      <webElementGuid>f3b7eee6-7b0e-4cb1-841a-b83b4de8f342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
