<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ST Segment Test 3192024</name>
   <tag></tag>
   <elementGuidId>3091c6df-2c91-4966-9ad6-3f35203366cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#segment_create--description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='segment_create--description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6f637771-3525-4770-8512-2a16f608cc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segment_create--description</value>
      <webElementGuid>64b44f9a-13fb-4aae-8868-4b89c1b40755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>109941e5-6d4d-4670-97e4-96afd31e8fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ST Segment Test 3192024</value>
      <webElementGuid>503be89d-9fba-4442-b619-c32ae205e6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segment_create--description&quot;)</value>
      <webElementGuid>d12c669e-6f0f-4bf4-a80c-592b03f687c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='segment_create--description']</value>
      <webElementGuid>27bf2746-6f77-4072-837f-28f318bdfc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::textarea[1]</value>
      <webElementGuid>875b25f6-5131-4cc5-b515-8ad33dba999c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::textarea[1]</value>
      <webElementGuid>1421833e-bf5a-4e2a-968b-72935486def5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>200ec17e-8e5a-4491-b286-c291612fc2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ST Segment Test 3192024']/parent::*</value>
      <webElementGuid>fe920b10-6684-4bd8-a1fd-88f5db2e46bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>678fdb0c-139d-4430-9b76-502f47bb695c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'segment_create--description' and (text() = 'ST Segment Test 3192024' or . = 'ST Segment Test 3192024')]</value>
      <webElementGuid>8afb841d-d31b-4e86-b357-9a34ff93cb96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
