<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Connect Button</name>
   <tag></tag>
   <elementGuidId>d13472b6-de76-49c1-989e-f7fc8f412b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='233']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss210.button_preview--title_container.jss201</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Brea Connect&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75396717-ea44-4740-a3a5-07058bcc6386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss210 button_preview--title_container jss201</value>
      <webElementGuid>27576c6b-0c80-4e19-90c5-bf4edcc24078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessibilitylabel</name>
      <type>Main</type>
      <value>container--button_preview-title</value>
      <webElementGuid>601d7896-93d3-4ab6-b768-24b34f0935c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brea Connect </value>
      <webElementGuid>e5fcf815-5dd8-4bef-ad4d-d4533d748d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;233&quot;)/div[@class=&quot;MuiBox-root jss210 button_preview--title_container jss201&quot;]</value>
      <webElementGuid>36f7345a-5c6b-4d8c-9e21-cf1918142eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='233']/div</value>
      <webElementGuid>7ba5a78d-770d-4e12-a380-8ed09d4a3997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kay Warren'])[1]/following::div[5]</value>
      <webElementGuid>d5c4b093-36e7-4bca-8283-61a9e3e1020b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paren DP'])[1]/following::div[5]</value>
      <webElementGuid>326a427b-4ff7-41db-8b94-9ec7719db764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>58292759-47e8-443a-8de3-33408917c9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Brea Connect ' or . = 'Brea Connect ')]</value>
      <webElementGuid>190d6879-06c6-4130-b350-d607b70f51f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
