<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QA Automation Follow Up Test List Item</name>
   <tag></tag>
   <elementGuidId>8cd66683-ec89-42bf-9875-2134ce49f422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cmui.grid--column.jss45.jss290</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83f00f5f-96ef-4c11-9405-e75ae8857c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui grid--column jss45 jss290</value>
      <webElementGuid>2ac3ebdd-927c-435a-bff6-3851a3d37723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui-grid_column</value>
      <webElementGuid>98197ee2-65e7-40e1-bec0-a2c405e54dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QA Automation Follow Up Test</value>
      <webElementGuid>af9a9186-eafd-4b8a-90f8-a218a37658a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_0&quot;)/div[@class=&quot;cmui grid jss7 jss288 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 jss290&quot;]</value>
      <webElementGuid>b32ab3fc-1634-4da5-8d95-de087cf479db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_0']/div/div[2]</value>
      <webElementGuid>5e34e1da-0312-4ed5-83c9-7c32940c81d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]</value>
      <webElementGuid>c2c7c9d9-9e69-46bf-afc5-f7944106e5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'QA Automation Follow Up Test' or . = 'QA Automation Follow Up Test')]</value>
      <webElementGuid>a3d801fd-be64-408e-8aff-02bec5f4c800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
