<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Done Button</name>
   <tag></tag>
   <elementGuidId>73ce221c-b7be-4855-b2e0-9aa5a282932c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@id,'custom_question--props_done_button--')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#custom_question--props_done_button--1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2610f24-8bba-4861-a3e5-70fe6eb9644c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui button jss243 jss1184 jss253</value>
      <webElementGuid>d6ba549d-b1af-4292-bb8f-64d4652f7663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom_question--props_done_button--1</value>
      <webElementGuid>64e27cc9-21ac-4805-a285-5e262fbcda55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>9225eb2b-3614-40c0-8165-aa2a593b6e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_question--props_done_button--1&quot;)</value>
      <webElementGuid>2f3b47ce-372a-4de6-925d-4dd594bc55f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
