<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Lower Environment Non-Smoke Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2860ae9d-4334-4343-9f63-6c8ccb1e01ad</testSuiteGuid>
   <testCaseLink>
      <guid>94f19048-4853-45e2-8dec-32ad8964a571</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Account and App Settings/User Management/Export Connection Forms</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ac76392-1831-4065-ae1e-6f994c559c01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbddfb86-2405-429d-8e58-ceaa80b5cd06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16014e38-bd12-48d7-a1d1-01cc024c7542</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f7ab851-fa4c-4cd5-9a10-996ad7be06c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Check In/Event Check In/All Spaces/Filter and Sort (Rooms)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3bb76dd-0a4c-45fc-8ce0-30979b4e59d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d06c8d9d-e97a-4bcc-9ed1-3d99385356f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Check In/Event Check In/Child Room/Create Person Record while Checking In</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87266c3d-1136-4712-ba48-9a26165a2720</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84f3078d-896d-4fa0-8d84-b78073dbdfe0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b9cd4c-1443-4a31-a9cb-fcf0b1cd43af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f056f715-2214-4bcf-a482-824f00785e06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec022273-745a-42df-b449-4402c4a06653</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae50b2a6-8b8a-47d9-b111-afef5be73b67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3ae7047-b387-4d0d-ba6a-8e046f9e0a7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Check In/Event Check In/All Spaces/Navigate to Person Record</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>797c436d-2307-4c18-9702-b97d2d3add11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>308c629d-d5a3-4eb9-a33a-0d3fcea8c34e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6599de59-e361-4ed6-ad37-723c78302b78</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Check In/Event Check In/All Spaces/Send a Notification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3031cc4b-e97e-44b0-b03c-ee54afeb8afb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bfb7932-feb8-4813-b05f-a8c0ff409e73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79fd93c3-afff-4d12-8d42-f8966cec1f7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcce6cdf-7ad0-4fc1-ad40-1e256d85e33f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Create an Event/Duplicate an Event</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e51b521-9a0f-4dc1-9470-d849379b4901</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcde9c14-b43b-4d60-bb5d-9275381ab01b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f20aa76-3e73-4dba-9e71-743d301921f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b462d966-ef34-4e38-95b4-8e1f68f19055</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79786b5a-a439-4109-b735-0ed0122a55cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7db016f6-a1f7-4da6-ab90-2092af001369</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Discover Events/Filter and Sort</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c51033e6-ccb4-43cc-8b2a-b8d70b224c21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Managing an Event/Edit an Event</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f323cc97-f7b4-4585-bf33-da6875363d7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5ef379b-8811-4734-b918-40ca57a33775</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a139494e-3a18-4d65-9a70-dfc06e99af19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>354f1114-f683-4e86-8b7d-6ac9e66383d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Managing an Event/Registration Roster/Send Email To Attendees</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d69ec155-cdff-452b-9e59-f04cfce8d639</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee9f961f-7ff7-4e08-ba7f-f97821117010</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/My Stuff/My Follow Ups/My Follow Ups Upcoming Claim Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2200d3a0-ef3b-4e41-81e5-e380d90fb731</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58ecaf8a-964a-4693-bc3a-fc731a02073d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/My Stuff/My Follow Ups/My Follow Ups Upcoming Reassign Task and Complete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6983845-abaa-4d7c-a57d-648cee4e64f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fd33baa-ed04-4000-af5a-b1605d2eeccb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/People/People Module Settings/Record Management</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24ca378-85c2-46ec-9973-a8cad396253b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>969a95a9-87b8-4fff-928b-e81912c6287d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Journey/Managing a Journey/Builder/Linear Journey Creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>695ad43a-07bf-4d1b-8e08-cae893b1c17d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3496a407-ce14-4d2b-97a1-f21963d470e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c53344e-439d-47f3-9931-1ff2f9deade3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1646af8a-e266-4403-b76c-41e8bb129312</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86f6effe-90c6-4252-bb93-71d4920e2814</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Journey/Managing a Journey/Builder/Open Nav Journey Creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e635431-a72a-4e15-81d6-81a36f26d045</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10ac3fde-306c-41f2-8c02-986f01fb566d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Create an Event/Create Event with Custom Fields and Sign Up</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23957d4c-5f8f-4180-865b-eee13fa28b5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65d7abbe-dd78-4376-a675-0ff067b682d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f559aaea-d54e-4456-abd1-57e290da305d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d12aab0d-60c7-4627-a374-a247702e1de4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ea2f0d8-5bc4-48b9-85ae-53149b567087</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Event Catalogs/Create New Catalog</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b1696f1-a7ad-42bf-8341-2dfb35c431cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>937dc69a-868a-4907-83ba-1be3a3132e89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Managing an Event/Accommodations</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>481f0b4b-002b-4407-8780-7b32d2d85d2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Managing an Event/Tags</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>51a62145-a9d6-41c9-9112-f47d92a3c8e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Managing an Event/Event Categories</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fc054961-a5bb-404c-a89a-ee06cf74d93c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Managing an Event/Room Categories</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f5e7fe00-f244-4e82-8330-1669209fb69a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Managing an Event/Service Categories</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d2ea51d9-8c72-45d0-a790-4327cf36d2c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/My Events/Filter and Sort</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>70b47435-32df-44eb-9969-f1d305ef3ad8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/My Events/My Events Search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6be775ec-265d-40fe-9e35-c0b5cef548a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b097f026-f6d3-435b-a5e9-20388fcca993</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef760e21-e1e3-4e1a-b29e-a3648b22d916</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ae4b041-752a-4116-8f56-6eee55eabe6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb0dcf7b-1305-4873-a310-ae262d2e539e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Serving Opps/Managing A Serving Opp/Communications/View Email History</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b644430d-b616-4b84-b55c-68b03a8c1508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>517636fe-6f43-48db-ad30-c28f0ea39118</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bd5acec-52e3-4eab-92e1-a27fab1d7f4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Serving Opps/Managing A Serving Opp/Roster/Send SMS to Multiple Members</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bb32f13-b6c2-4754-838b-4b06ccebb3e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>706b1884-8127-44e1-ab99-46a7d8033e59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4e14f3f-5153-41cd-8c79-073a2c67c50c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52927145-8831-42ef-8588-4f7ea77bc042</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Serving Opps/Managing A Serving Opp/Serving Schedule/Send Email to Serving Schedule</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d250bed5-94f6-401f-8d8e-c14aaeae1bf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b625b23-d546-4e07-8c65-01a263e32f81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33103c4b-4e3e-4037-a39b-5c2596fa67e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a2adc10-a21c-414f-8e9d-a29786fbb027</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Data Capture/Connection Forms/Form Builder/Create New Connection Form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ebbb329-fa18-411c-838e-c7ebfc83bb26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a407740b-19b2-4adb-8128-8b5568f37064</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
