<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prod Approved Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>824eebf5-3cf0-48b9-a011-f3b6ccca7257</testSuiteGuid>
   <testCaseLink>
      <guid>621d5364-8bbc-474d-a77e-63e16bcf3e45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Shared/Verify Component Versions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b5d36787-2fab-4a15-8d78-a1fe81d65ee6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Data Capture/Forms/Published Forms/Connection Form Public Authenticated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b06834cc-4bfe-4778-96a2-47021adc4153</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1509d933-8280-475f-a59b-8341f842b6c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf360bff-8150-4c00-8472-98afab34770b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Data Capture/Forms/Published Forms/Connection Form Public Unpublished</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b510abfe-2b8e-4cfa-9d6c-0938228ee129</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Events/Create an Event/Event Search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaf2f96f-f1b8-4232-84af-55f8811e4ce2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecb56182-3846-412e-afcf-51a321c85801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b43df2bb-486a-4609-9a56-332225fc75db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ec26b8-a5ae-4e47-8558-d21b0ee160d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4420bab7-2bd9-4251-8c61-c4bcab5e98ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ab4e277-fe2a-470a-8181-d8b37bc97163</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Ministry/Navigation/Ministry Search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dd511c0-60cd-48f5-a519-fe8328504ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5375c838-c981-4fe3-be61-7c43e5ea1aef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>693a1173-6038-4b12-b3e3-feec3bb6d235</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbe3d360-b751-48ad-bd20-f475e4bd858c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8837e34b-942c-4ae4-bc62-5fde1803aa6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccdd1f9a-aa0b-4d88-a067-409d4ec6d0b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/Navigation/All Nav</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1a7028f8-53d2-49b1-9b50-95d23f9ef43e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HC-Web/People/People Search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26ce4b9-ff1a-41a2-bbcf-7d07d375db81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>535d2097-cdd3-47c6-b508-8cef521a0a7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82b2d77e-024c-4719-88e1-9e8fdcdcedf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80ed7adf-9029-49e4-adef-b8aafd501455</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
