<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open Navigation Journey</name>
   <tag></tag>
   <elementGuidId>3f9a8539-5037-48ec-b848-65419ced73ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[11]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ddfb8498-b9bd-4eda-bf6f-9c76348252b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44bd2acd-3873-473f-afb7-02a41b3109fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-item</value>
      <webElementGuid>3767270f-59a5-486e-9b99-3e5278b69c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>88a56ab5-5753-405b-a235-f4af8e88115a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3220f1ad-6482-41b3-ad68-625c79ea10c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Navigation Journey</value>
      <webElementGuid>e1930e9d-733d-4a61-b8c6-dd1b8bd52cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;safari&quot;]/body[@class=&quot;design-v1 drawer-open drawer-dimmers&quot;]/div[6]/div[@class=&quot;ui drawer jss201 journeys_list_page--add_drawer drawer-is_modal drawer-has_title_bar drawer-has_action_bar&quot;]/div[@class=&quot;drawer-container&quot;]/div[1]/div[1]/div[@class=&quot;drawer-container-inner&quot;]/section[@class=&quot;ui jss364 drawer--content journeys_list_page--content&quot;]/div[1]/div[@class=&quot;cmui grid jss7 jss371 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 jss372 jss68&quot;]/div[@class=&quot;ui radio jss332 jss328 radio-pill&quot;]/div[@class=&quot;radio-item&quot;]</value>
      <webElementGuid>0e783b5e-8053-408d-ba5e-603fce52f70e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]</value>
      <webElementGuid>e371b678-8e57-4df1-a67e-5dd9605e485b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Open Navigation Journey' or . = 'Open Navigation Journey')]</value>
      <webElementGuid>b37f11ab-3cdd-4c88-bd24-71f50b7d34be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
