<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sbchcqagmail.com</name>
   <tag></tag>
   <elementGuidId>16f64406-cba2-4126-82db-4aa3cd97d95c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jss511</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='data_grid--table_user_search_drawer--data_grid_cell_base-2_0']/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9e16fd7-b8fe-4e53-894b-98112823a803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss511</value>
      <webElementGuid>64107fd4-4968-4261-b977-fef156f5d51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sbchcqa@gmail.com</value>
      <webElementGuid>1bd3ce6f-ae93-44fd-843a-407481a4b113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_grid--table_user_search_drawer--data_grid_cell_base-2_0&quot;)/div[@class=&quot;jss506&quot;]/div[@class=&quot;jss509&quot;]/div[@class=&quot;jss508&quot;]/div[@class=&quot;jss511&quot;]</value>
      <webElementGuid>3ed9df0c-45b0-43e7-9380-3bf1f552a7a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='data_grid--table_user_search_drawer--data_grid_cell_base-2_0']/div/div/div[2]/div[2]</value>
      <webElementGuid>31f58840-6885-40dd-8251-da11d3530a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div[2]/div[2]</value>
      <webElementGuid>0bfd8d9d-2560-4950-9958-968529369788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'sbchcqa@gmail.com' or . = 'sbchcqa@gmail.com')]</value>
      <webElementGuid>28bb539c-b498-446a-b646-3be3ef6c3a4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
