<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create New Event</name>
   <tag></tag>
   <elementGuidId>c0049bc8-f65c-4d83-b961-9c1568fc890b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1 > div.dropdown_menu--option_inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4bb2e275-8168-442f-b735-d1e9532f0151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_menu--option_inner</value>
      <webElementGuid>39dc203d-d9a7-44c4-bc48-f8a966be6431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Event</value>
      <webElementGuid>4de6a59a-2fdd-4471-a2a2-588fe20390f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-dropdown--events_new_event&quot;)/span[@class=&quot;button-inner-container jss244&quot;]/div[@class=&quot;ui dropdown_menu button_dropdown--menu jss229 jss389 jss204 jss231 dropdown_menu-opened&quot;]/div[@id=&quot;1&quot;]/div[@class=&quot;dropdown_menu--option_inner&quot;]</value>
      <webElementGuid>25be0400-7c96-4574-89c0-0243a92014a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div</value>
      <webElementGuid>142cbcf4-f0b9-4731-a745-53e869628c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[2]/div/div</value>
      <webElementGuid>dc0e6f43-145f-4016-bfec-6ec31da4245e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create New Event' or . = 'Create New Event')]</value>
      <webElementGuid>72dcf1ee-5bac-4607-9bc1-5292e5eb6ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
