<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NewEventDropdown_button</name>
   <tag></tag>
   <elementGuidId>cb9c70e9-5cbf-4873-9114-96dd4be940f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ui-dropdown--events_new_event']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-dropdown--events_new_event</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04c5b91c-7c94-44ec-95f2-81c16de042b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>21db325e-d7a0-4e31-9b35-dafde6ce7a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui button jss243 jss388 jss205 button_dropdown jss255</value>
      <webElementGuid>5a1631a2-e739-4913-a045-8c3f41e0bed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-dropdown--events_new_event</value>
      <webElementGuid>7bdc1e2a-7fdc-4d6f-b817-0da3228712c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>chevron-downNew EventCreate New EventRequest Paid Event</value>
      <webElementGuid>4b9acedd-b565-4e6e-b73d-4a0ae4106b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-dropdown--events_new_event&quot;)</value>
      <webElementGuid>ecd2180a-d274-4320-a87b-4cff199f5ca5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
