<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Actions</name>
   <tag></tag>
   <elementGuidId>696ab6a0-0d7e-48b7-9e18-f99ec6425caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dropdown-selection-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='occurrence_schedule--actions_dropdown_button']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06d46724-66a0-472d-98ee-01a1567f6f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-selection-value</value>
      <webElementGuid>22d11e17-57a7-49e4-b74d-ade9d13d36c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>cc12699d-7139-4453-8773-44a90abd4be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occurrence_schedule--actions_dropdown_button&quot;)/span[@class=&quot;dropdown-selection-value&quot;]</value>
      <webElementGuid>0b1022da-1dc8-485b-9436-876ad581a606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='occurrence_schedule--actions_dropdown_button']/span</value>
      <webElementGuid>5bda56f0-93f5-45ec-890f-efe49767555e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span</value>
      <webElementGuid>69709ade-70cc-43e3-8591-de98637cc0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>63fbe343-bf4d-4d53-ae65-22af72ee698c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
