<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to Roster</name>
   <tag></tag>
   <elementGuidId>76ad8ee2-c6fa-4469-a3a1-592122d37b4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='occurrence_schedule--roster_actions_dropdown_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#occurrence_schedule--roster_actions_dropdown_button > span.dropdown-selection-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>411f62cb-ffb8-461a-b7d5-fcd915d2670e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-selection-value</value>
      <webElementGuid>889d64d8-e9b7-40c6-838b-20d48104bfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Roster</value>
      <webElementGuid>76b711e6-82b8-4f39-a091-614cd3c9e4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occurrence_schedule--roster_actions_dropdown_button&quot;)/span[@class=&quot;dropdown-selection-value&quot;]</value>
      <webElementGuid>6345696d-913e-4513-b1ba-358517237d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='occurrence_schedule--roster_actions_dropdown_button']/span</value>
      <webElementGuid>9be141d3-d6f0-4121-be44-00b12818c1f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
