<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Remove From This Occurrence</name>
   <tag></tag>
   <elementGuidId>68405d2d-3d98-418d-ba78-5b2e70a4c92e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#occurrence_schedule--actions_dropdown_button_9 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='occurrence_schedule--actions_dropdown_button_9']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a1bcecd-da87-48fe-8bbc-4747395eb534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove From This Occurrence</value>
      <webElementGuid>b07dcc05-77e6-46af-9afb-2f811bd31a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occurrence_schedule--actions_dropdown_button_9&quot;)/span[1]</value>
      <webElementGuid>1a238012-8586-49fc-8e77-5393b5e097ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='occurrence_schedule--actions_dropdown_button_9']/span</value>
      <webElementGuid>96508f1b-ada3-4886-a5d1-6625d0285059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>c12fead9-6d47-45d2-9306-8c4da71973a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Remove From This Occurrence' or . = 'Remove From This Occurrence')]</value>
      <webElementGuid>e4a9be41-f9e5-466c-ac4e-de3061d67384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
