<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_chevron-downNew EventCreate New EventR_321259</name>
   <tag></tag>
   <elementGuidId>681df82f-8a35-4db5-b7bd-bcd3dda7e227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.button-inner-container.jss244</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ui-dropdown--events_new_event']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b75fd500-9f09-447b-a16b-ed191857f4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner-container jss244</value>
      <webElementGuid>5ae60ecb-f17b-4781-9cd0-63b3b7b0fc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>chevron-downNew EventCreate New EventRequest Paid Event</value>
      <webElementGuid>1477e46d-ebaf-423e-95d3-1c7cb4cca4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-dropdown--events_new_event&quot;)/span[@class=&quot;button-inner-container jss244&quot;]</value>
      <webElementGuid>2307747c-1093-42ee-a1d7-a5c5daa42962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ui-dropdown--events_new_event']/span</value>
      <webElementGuid>5fc3e1ac-1045-46c2-bd65-71edc4499bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>d477181b-b01b-40e4-8df3-f50f997b7692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'chevron-downNew EventCreate New EventRequest Paid Event' or . = 'chevron-downNew EventCreate New EventRequest Paid Event')]</value>
      <webElementGuid>390da24c-a1e6-4865-a6c8-baed4418bfb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
