<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Follow Ups</name>
   <tag></tag>
   <elementGuidId>48e66d8a-374a-40e8-a5c2-35c0216df9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-navigation_tab--key-item-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-navigation_tab--key-item-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>044fe5e8-61a5-4b5b-a434-d0ad41c1537e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b7aa443-c5dc-4467-9765-6b2aa9aebdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss421 navigation_sectional_tabs--tab</value>
      <webElementGuid>9a93a90c-baa4-4a5b-b7c3-587f35c23c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-navigation_tab--key-item-4</value>
      <webElementGuid>386a51b9-f7ca-4bcc-b7f3-784c7b03d8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>673eaf6f-7158-4c1b-bae2-97141197a9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>be667e7e-0a8f-438d-b1a8-18d479f21763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51bbbf88-43cf-49e3-a9c5-d83f0f4832e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Follow Ups</value>
      <webElementGuid>6031dcd9-264a-4336-80ce-3eb467b02123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-navigation_tab--key-item-4&quot;)</value>
      <webElementGuid>177aa602-1974-442c-b639-4d227453c8b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tab-navigation_tab--key-item-4']</value>
      <webElementGuid>c49962cc-ad1c-4127-a5a9-43e7d36ede65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div/div[2]/div/div/div/div/div[2]/div/div/button[5]</value>
      <webElementGuid>fdb93054-e58f-43c8-ab70-4ab95b8f09cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto-Reply Email'])[1]/following::button[1]</value>
      <webElementGuid>1ff9ac17-4a4b-44b9-8370-86e2032d1ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Builder'])[1]/following::button[2]</value>
      <webElementGuid>bb9aba04-5671-478a-9bf0-7ba4e39af33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[1]/preceding::button[2]</value>
      <webElementGuid>f017912a-2c5e-4d84-84b7-3c6d3ba5d1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>033e2e54-80d8-4899-8d37-56a7e2a9ba80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tab-navigation_tab--key-item-4' and @type = 'button' and (text() = 'Follow Ups' or . = 'Follow Ups')]</value>
      <webElementGuid>e110e2c6-ed95-4e76-99cc-ccc4dbb87d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
