<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notifications</name>
   <tag></tag>
   <elementGuidId>f5be2cf7-886b-4347-a442-c2f62defeed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='task_action_form']/div[10]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiTypography-root.MuiTypography-h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#task_action_form >> internal:text=&quot;Notifications&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e58a833-7609-4500-af0b-23f0772aad41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h3</value>
      <webElementGuid>fa7f33d8-18ec-4cf6-b0bf-4c7a14c1b597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>dd78de7a-6b86-45fb-915f-c76c558372fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_action_form&quot;)/div[@class=&quot;cmui grid--column jss45&quot;]/div[@class=&quot;MuiTypography-root MuiTypography-h3&quot;]</value>
      <webElementGuid>412ea90e-931a-45fc-98b9-4725c8dbae70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task_action_form']/div[10]/div</value>
      <webElementGuid>67b964a2-ef63-48c1-98e1-955961a5e154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[2]/following::div[2]</value>
      <webElementGuid>c032f9fb-2d12-4cd9-89e6-af7a6e8fee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sarkisiansarkis2@gmail.com'])[1]/following::div[2]</value>
      <webElementGuid>3c058e39-ea62-4b08-81c2-9ef3c9000ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[1]/preceding::div[1]</value>
      <webElementGuid>4f79234e-51e6-40ef-853e-f7bf98d2026f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily batch'])[1]/preceding::div[2]</value>
      <webElementGuid>04b63ca2-4262-4c37-ac00-aed196413ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div[10]/div</value>
      <webElementGuid>6cf20369-acd0-4041-bf7c-f338d3b8ccfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Notifications' or . = 'Notifications')]</value>
      <webElementGuid>4ae84638-9fe6-4346-a0fe-ba156968d4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
