<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_chevron-wl-right</name>
   <tag></tag>
   <elementGuidId>ae6a5bfc-cf05-4636-aa9e-f40f0063765c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui.button.jss245.jss1500.jss1488.jss250.jss260 > span.button-inner-container.jss246</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/main/div/section/div/div[2]/div/div/div/div/div[5]/table/tbody/tr[3]/td[4]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1b5a2316-1ae6-4f31-b23f-121a66486b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner-container jss246</value>
      <webElementGuid>36dc679f-5b7c-49cf-b686-a68e8041790b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>chevron-wl-right</value>
      <webElementGuid>59f4a586-4c6f-458d-bfc6-edc2d3b695e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss1399 jss1490&quot;]/div[@class=&quot;cmui container jss1426 ui page--container jss1425&quot;]/section[@class=&quot;cmui content jss1429 ui page--content jss1428&quot;]/div[@class=&quot;jss1483&quot;]/div[@class=&quot;cmui grid jss7 jss35&quot;]/div[@class=&quot;cmui grid--column jss45 jss68 jss93 jss104&quot;]/div[@class=&quot;ui card jss244 jss1487&quot;]/div[@class=&quot;card-content&quot;]/div[1]/div[5]/table[@class=&quot;ui jss1494 table table-basic table-font-size-xsmall table-full-width table-selectable jss1482&quot;]/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;table-row table-row-clickable&quot;]/td[@class=&quot;table-cell table-cell-one jss1485&quot;]/button[@class=&quot;ui button jss245 jss1500 jss1488 jss250 jss260&quot;]/span[@class=&quot;button-inner-container jss246&quot;]</value>
      <webElementGuid>ae09c19f-f7f8-4dba-9a5c-830be15250dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div/div[2]/div/div/div/div/div[5]/table/tbody/tr[3]/td[4]/button/span</value>
      <webElementGuid>aadbb3a4-2da7-40ba-82f5-25a67546c2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox'])[1]/following::span[1]</value>
      <webElementGuid>f433cf0c-18a0-4588-aa56-8eb8f7fae1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CTA Single Check Box'])[1]/following::span[1]</value>
      <webElementGuid>a513f4f4-7ed7-412e-9303-67232421af12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Help Resources'])[1]/preceding::span[1]</value>
      <webElementGuid>dc1c45aa-ab45-4877-80a2-2c82bef8c2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Management'])[2]/preceding::span[2]</value>
      <webElementGuid>ad20b594-2341-4909-81b5-1626cb2695e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/button/span</value>
      <webElementGuid>439863ca-36c3-4cba-8426-468a8a43eab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'chevron-wl-right' or . = 'chevron-wl-right')]</value>
      <webElementGuid>05ce6840-980e-437f-a58b-b26654e97b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
