<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Detailed Follow Up Push Notification</name>
   <tag></tag>
   <elementGuidId>4a1be64d-a8ce-49f4-ad13-820b5da682e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-49--value-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='react-select-49--value-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>34f829d8-acea-4093-9b54-dc62f2169cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-value-label</value>
      <webElementGuid>66f5dbff-f489-4408-a8f4-dac59f12ed99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d50a938a-a503-4b50-952c-f064d8ee2a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52c85bb8-eb2e-43a7-9985-bf0849a65692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-49--value-item</value>
      <webElementGuid>d88def93-c268-4a8f-9a5b-1d6e69cfe278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detailed Follow Up Push Notification</value>
      <webElementGuid>911adf7c-0174-4da8-8203-7f96b3fa6280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-49--value-item&quot;)</value>
      <webElementGuid>48328c2a-b736-4640-a06e-cdfe47418971</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='react-select-49--value-item']</value>
      <webElementGuid>e59c7bdc-242c-4079-846d-6094b871224a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-49--value']/div/span</value>
      <webElementGuid>8b02c752-2c43-412b-a248-246b9c019eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple Follow Up Push Notification'])[1]/following::span[1]</value>
      <webElementGuid>50527e57-dcd1-48fd-a6cc-12db78024ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important Follow Up Push Notification'])[1]/following::span[1]</value>
      <webElementGuid>5681d8ee-88bb-4c9d-8928-2452d0101d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::span[2]</value>
      <webElementGuid>19673d0d-e931-47ec-93e3-368e0d5eae8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Task'])[2]/preceding::span[3]</value>
      <webElementGuid>ca739af9-d4f4-4328-8c3c-49b560fdca5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/span</value>
      <webElementGuid>ce9f75b3-3cce-496c-b353-c4a5cd5e505c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'react-select-49--value-item' and (text() = 'Detailed Follow Up Push Notification' or . = 'Detailed Follow Up Push Notification')]</value>
      <webElementGuid>2095fa32-a297-4d0b-b20b-9e418c1b7808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
