<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Paren Anaheim Worship 1_data_grid--table_25920f</name>
   <tag></tag>
   <elementGuidId>b1df921e-c3a1-4146-8ac8-f54280c431bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6e65a87d-bae9-43ed-864c-087cd03c4d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-cell jss1119</value>
      <webElementGuid>f2a51741-c2e2-40d8-aeb4-ad6a28c12b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1</value>
      <webElementGuid>d2469520-9c6b-496a-bc1d-3a90de408770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1&quot;)</value>
      <webElementGuid>30e92499-fbcd-4339-b222-8c327cc7bfb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1']</value>
      <webElementGuid>44adab84-551a-42a8-a8f0-0ef08bc7c93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div/div/div/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>f14cb103-b252-4e64-a8bd-6422f319af99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paren Anaheim Worship 1'])[1]/following::td[1]</value>
      <webElementGuid>0ff7432a-afe2-4d49-bc8f-15ed57e0711f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::td[2]</value>
      <webElementGuid>3d7ac5ee-1f00-482f-8f82-e107bcfd4bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anaheim'])[2]/preceding::td[2]</value>
      <webElementGuid>c2e7b4b3-cd87-4662-b916-d909c4eeaf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Worship Service'])[1]/preceding::td[2]</value>
      <webElementGuid>04f9cb73-78d7-454b-816b-abf5729f47e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>c5472ae0-ccd4-4fc7-8086-99bad88fe7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1']</value>
      <webElementGuid>114397f8-ed11-4fe8-be20-e6a3e0a27388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
