<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No</name>
   <tag></tag>
   <elementGuidId>e8534227-d4c6-461a-93f2-6d661074a4cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form_entry_editor--actions_dropdown_button_menu']/parent::div/following-sibling::div/div[@class='prompt-no-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
