<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Yes</name>
   <tag></tag>
   <elementGuidId>288e912b-0dcb-4111-b938-c765fac83016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form_entry_editor--actions_dropdown_button_menu']/parent::div/following-sibling::div/div[@class='prompt-yes-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
