<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Teams_user_search_drawer--action_bar_search</name>
   <tag></tag>
   <elementGuidId>16eec2a6-331d-4177-b61d-69f4f3a27f88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_search_drawer--action_bar_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_search_drawer--action_bar_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;cmui--search_input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4933807-1c64-498d-9a77-3a5341a2541d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui--search_input</value>
      <webElementGuid>a7f70672-4b17-44ff-af14-ff121c8bc3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_search_drawer--action_bar_search</value>
      <webElementGuid>8d6ed81c-6867-4b36-b309-479a8fbcc6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>59654fca-57e5-4973-95d5-2b401e5635d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84cac1f9-d308-4708-8d88-04488c2fc828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>cb7085c6-8385-4d7e-b6be-33c7d8209ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_search_drawer--action_bar_search&quot;)</value>
      <webElementGuid>a3efcb66-3402-4943-ac59-e5767aca9b06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_search_drawer--action_bar_search']</value>
      <webElementGuid>99a94f1f-b703-490f-a728-1ba92f7b494f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div[2]/div/div/input</value>
      <webElementGuid>4383dac9-7fa8-428d-94be-906c22f93269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_search_drawer--action_bar_search' and @placeholder = 'Search' and @type = 'text']</value>
      <webElementGuid>217d5c5f-f29f-4b38-931c-9a8c40c9dd67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
