<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__task_action_form--task_name_input</name>
   <tag></tag>
   <elementGuidId>415809dd-62dc-4c78-a7c6-5d74699f827a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task_action_form--task_name_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='task_action_form--task_name_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Give this task a name...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e418364f-5760-4570-bbca-38487d90b234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task_action_form--task_name_input</value>
      <webElementGuid>46466101-7d09-4949-9914-3220e967683a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give this task a name...</value>
      <webElementGuid>922529db-3b85-4a5f-8db3-0e5da8695694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1eef99ab-3ae3-4a87-9e40-f39195b59535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_action_form--task_name_input&quot;)</value>
      <webElementGuid>006d226c-72f8-42c6-bc6d-c691bad915b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='task_action_form--task_name_input']</value>
      <webElementGuid>53d82e19-08e5-4305-9ce1-0fce4c609f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task_action_form']/div[3]/div/input</value>
      <webElementGuid>f066dabf-2773-45d5-ab63-44e1ebecdc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2a2ad270-4908-44bd-91bb-7c77d19a91c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'task_action_form--task_name_input' and @placeholder = 'Give this task a name...' and @type = 'text']</value>
      <webElementGuid>0e2a0d4a-654b-4e0e-a9c1-a6f33e0d6ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
