<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_PAW1 Task Instruc</name>
   <tag></tag>
   <elementGuidId>601f9fda-bc7f-4b74-b3d0-b46a22f37785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task_action_form--task_instructions_textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='task_action_form--task_instructions_textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Give this task instructions...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>db8d344e-be54-4b0c-8303-4d7418450550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task_action_form--task_instructions_textarea</value>
      <webElementGuid>0a8b1cf9-0ac0-4fdc-a30a-59a63505de89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give this task instructions...</value>
      <webElementGuid>6082f011-a6d3-405c-8faf-2b137984ca4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAW1 Task Instruc</value>
      <webElementGuid>5e591b8b-e778-4ca1-a8ce-29884900727d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_action_form--task_instructions_textarea&quot;)</value>
      <webElementGuid>ab309c29-93f8-4337-9ef5-00527c086282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='task_action_form--task_instructions_textarea']</value>
      <webElementGuid>5733efea-2a80-4338-b8c0-02c4b83309d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task_action_form']/div[4]/div/div/textarea</value>
      <webElementGuid>6b8afdf0-e282-4711-8533-5303c970132a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task Instructions'])[1]/following::textarea[1]</value>
      <webElementGuid>520c1c1b-6c7e-4131-a6b9-95a3c55088cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task Name'])[1]/following::textarea[1]</value>
      <webElementGuid>21ecdee0-3024-4bb3-9c18-711b3b36fb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>08618b9a-1ad4-487b-8561-4b274bfafb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAW1 Task Instruc']/parent::*</value>
      <webElementGuid>69ae86ae-18ae-4b0e-a0de-c89edfa13409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e7d27aa6-4fa4-4193-9903-bc00a1dd5a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'task_action_form--task_instructions_textarea' and @placeholder = 'Give this task instructions...' and (text() = 'PAW1 Task Instruc' or . = 'PAW1 Task Instruc')]</value>
      <webElementGuid>a52130c5-feb5-4b8f-9e43-6147f36153ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
