<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_PAW1 rule descrip</name>
   <tag></tag>
   <elementGuidId>114b042c-651f-4f99-b973-51100f43c08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#follow_up_rule_editor_drawer--rule_description_textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='follow_up_rule_editor_drawer--rule_description_textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Write a rule description...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a297583c-4d55-47f9-8ff7-c0d6b0b9c555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>follow_up_rule_editor_drawer--rule_description_textarea</value>
      <webElementGuid>f4b4a754-db5b-4ca3-80f1-a10272c6fd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write a rule description...</value>
      <webElementGuid>63d71843-4af1-4567-8631-5858f04cfaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAW1 rule descrip</value>
      <webElementGuid>8b5e337e-4015-4995-b3a6-f19202350607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow_up_rule_editor_drawer--rule_description_textarea&quot;)</value>
      <webElementGuid>8c3d183f-798f-46cc-8f98-408098365bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='follow_up_rule_editor_drawer--rule_description_textarea']</value>
      <webElementGuid>62004c2f-1e9d-47e6-971e-b08e8414d7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow_up_rule_editor_drawer--left_panel_basic_info_editor']/div[5]/div/div/textarea</value>
      <webElementGuid>4b99ed06-3aa5-4f08-aff0-54d70a0e785c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::textarea[1]</value>
      <webElementGuid>53c74d8b-3c22-4cf3-8420-7c6026414481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anaheim'])[3]/following::textarea[1]</value>
      <webElementGuid>403c0ca3-2f9c-421b-bb9e-13a92f5bec52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4eed6e61-bca3-4d7c-9b31-0c7cda4e77a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule Details'])[1]/preceding::textarea[1]</value>
      <webElementGuid>29d20c92-5a54-4fb1-ad17-c56609428dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAW1 rule descrip']/parent::*</value>
      <webElementGuid>5ef4eb2f-bd73-4180-a757-0d7434643ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>25fa3c03-b8f4-4611-b84b-86aadea55703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'follow_up_rule_editor_drawer--rule_description_textarea' and @placeholder = 'Write a rule description...' and (text() = 'PAW1 rule descrip' or . = 'PAW1 rule descrip')]</value>
      <webElementGuid>38ddad9b-359e-4b9c-8263-ff74f815aa00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
