<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_PAW1 Task Instructio</name>
   <tag></tag>
   <elementGuidId>1c45ead6-34be-4130-a7c1-3056f3412aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task_action_form--task_instructions_textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='task_action_form--task_instructions_textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Give this task instructions...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3a8c7e96-7a1f-4dc6-a07c-414fe1efafc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task_action_form--task_instructions_textarea</value>
      <webElementGuid>9c00539d-708a-41c8-b8ae-661285eb4d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give this task instructions...</value>
      <webElementGuid>f2ec665e-587c-4808-be33-8885958f186d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAW1 Task Instructio</value>
      <webElementGuid>244f26c0-32ce-42f9-bf90-edfd0b054b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_action_form--task_instructions_textarea&quot;)</value>
      <webElementGuid>1028c6fb-737f-4b7e-b96f-aacd35278570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='task_action_form--task_instructions_textarea']</value>
      <webElementGuid>4d67511a-32db-463d-b286-ac32fc893dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task_action_form']/div[4]/div/div/textarea</value>
      <webElementGuid>6526db66-85de-48d7-8e82-a12188e471bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task Instructions'])[1]/following::textarea[1]</value>
      <webElementGuid>f896f7c1-3165-4ec1-983f-59ef40a90398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task Name'])[1]/following::textarea[1]</value>
      <webElementGuid>dfddca35-bbf6-4302-bfbf-1aa0b662cc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>1ec19a57-c4c1-4df5-8039-84fa16c27311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAW1 Task Instructio']/parent::*</value>
      <webElementGuid>c93a69c7-2acd-419a-84d8-67fdd52bf3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7ab3a781-ded9-400f-b951-8ebec9b27531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'task_action_form--task_instructions_textarea' and @placeholder = 'Give this task instructions...' and (text() = 'PAW1 Task Instructio' or . = 'PAW1 Task Instructio')]</value>
      <webElementGuid>55e5ce62-0609-4b7c-ae50-3b48eff2829a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
