<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Connection Form row</name>
   <tag></tag>
   <elementGuidId>b1df921e-c3a1-4146-8ac8-f54280c431bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e4313a7c-f70e-4c59-9acd-d18244cf921d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-cell jss1119</value>
      <webElementGuid>2a9eff2a-728c-47c6-925b-15af0d386e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1</value>
      <webElementGuid>f15c9395-25df-4c11-9938-23a7e8a86394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1&quot;)</value>
      <webElementGuid>bb7c77c4-19bb-44ed-bcc9-7fafe3856665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1']</value>
      <webElementGuid>c202b05e-39c5-4241-bcad-ce51718a9e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div/div/div/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>e2c341f5-925c-43a2-847e-b7479ac29335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paren Anaheim Worship 1'])[1]/following::td[1]</value>
      <webElementGuid>8e37ca41-92db-4a18-8568-75d2237ff929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::td[2]</value>
      <webElementGuid>96c3b28f-6ef2-4fbd-b6fa-ba5b5274b30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anaheim'])[2]/preceding::td[2]</value>
      <webElementGuid>56c472b0-b0e0-4e73-a33f-217a0642cbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Worship Service'])[1]/preceding::td[2]</value>
      <webElementGuid>5d3331b1-9133-4278-86bb-89f060fd74aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>ffb58e28-6855-4938-acfe-787f671dbafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'data_grid--table_connection_forms_list_page--page_data_grid_cell_base-2_1']</value>
      <webElementGuid>16b5c7fa-9587-4bbd-b832-2f4290f29e09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
