<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Location Footer Link</name>
   <tag></tag>
   <elementGuidId>ec5277de-325c-4530-a523-8bc4a3642c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.footer-nav-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@class='footer-nav']/li/a[contains(text(),'Locations')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e21901b2-f665-49db-97c6-f33e36e9beb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/locations/</value>
      <webElementGuid>e62c67c5-ade8-408a-ba91-a8d74c1b90ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-nav-page</value>
      <webElementGuid>ac76d7c0-2391-404e-9c3d-3c1b99a2b079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Locations</value>
      <webElementGuid>d89bc7b6-3b1e-45f6-b833-9477aa9f5e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;header-desktop-menu desktop-center&quot;]/ul[1]/li[1]/a[@class=&quot;footer-nav-page&quot;]</value>
      <webElementGuid>55d7a330-0c84-49a2-9448-539c46b37d8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Locations')]</value>
      <webElementGuid>affc0306-83dc-45dc-b35e-f94715964f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/locations/')]</value>
      <webElementGuid>d408fd45-cd2a-406a-aeab-11392533ebbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>db68487d-945c-4a0a-8cf6-8af83010be3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/locations/' and (text() = 'Locations' or . = 'Locations')]</value>
      <webElementGuid>76968cec-fc29-4ddc-a04e-059d4246c60b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
