<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CancelApply</name>
   <tag></tag>
   <elementGuidId>4e38729f-09f2-4d46-942b-b110b432d5db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal--actions.jss2193.jss1680.jss2192.jss2185.jss2191</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a22efab2-20f6-4542-a05a-02784aa3b8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal--actions jss2193 jss1680 jss2192 jss2185 jss2191</value>
      <webElementGuid>084dbd0a-e36d-4c8f-afff-b3a9cfe8a4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CancelApply</value>
      <webElementGuid>1ddf0277-30c8-408a-b467-0dfbd6164e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hc-ui safari&quot;]/body[1]/div[7]/div[@class=&quot;cmui modal jss1668 jss1681&quot;]/div[@class=&quot;modal--inner_container jss1666&quot;]/div[1]/div[1]/div[@class=&quot;jss1669 jss1667&quot;]/div[@class=&quot;modal--actions jss2193 jss1680 jss2192 jss2185 jss2191&quot;]</value>
      <webElementGuid>459639aa-baf0-4408-9e26-bf95d95fe43e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[20]</value>
      <webElementGuid>de1889a0-6994-4bce-8231-88f94891d72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div[2]</value>
      <webElementGuid>4cabe193-fc25-41c0-b49c-eb38f8ce4203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CancelApply' or . = 'CancelApply')]</value>
      <webElementGuid>dc673ea0-f768-4e29-8846-cf77686f1c1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
