<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form_entry_editor--question_22945</name>
   <tag></tag>
   <elementGuidId>409d08e0-2b00-4fc0-b0c2-400e3c291a81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_entry_editor--question_22945']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_entry_editor--question_22945</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ce3f1c1-a212-4b85-bb8f-0599a3c15086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_entry_editor--question_22945</value>
      <webElementGuid>2953661c-b87f-4a13-aef9-b621dd840083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PHT</value>
      <webElementGuid>aa26bee7-95bd-4256-ab0a-253529f24689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf864169-e8c7-4007-a8e3-e4f068a15386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>790c9207-c153-4f26-9632-e39c423a4085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_entry_editor--question_22945&quot;)</value>
      <webElementGuid>c28d218d-2eb3-4e4c-a4d2-0de17ce63780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_entry_editor--question_22945']</value>
      <webElementGuid>e254dbdf-84ff-4422-83fe-6c61f3277ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div[2]/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>c08b68b5-c1f7-43ac-b3b8-de7dcc6d17e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>39a4f800-1fe9-43e0-be4f-9cdb757f9e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_entry_editor--question_22945' and @placeholder = 'PHT' and @type = 'text']</value>
      <webElementGuid>a94cf037-6ddb-45c8-aeab-5a940e6e427b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
