<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>f39e6bc1-7080-4304-b938-919f01b50dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='person_panel--select_record_btn']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#person_panel--select_record_btn > span.button-inner-container.jss208</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a8911a3d-1111-4742-bc04-2b1005618d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner-container jss208</value>
      <webElementGuid>fdf561d1-aa2c-4cf0-a195-2b941998cd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>2932d9f4-81a0-4ad4-b05f-9af8348be4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;people_search_drawer--results&quot;)/div[@class=&quot;jss651 jss646 cmui person_panel&quot;]/div[@class=&quot;jss678 jss644 jss649 cmui person_panel--details jss676&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[@class=&quot;jss675&quot;]/div[@class=&quot;jss673&quot;]/div[@class=&quot;ui prompt jss571 jss785 prompt-inline&quot;]/div[1]/button[@id=&quot;person_panel--select_record_btn&quot;]/span[@class=&quot;button-inner-container jss208&quot;]</value>
      <webElementGuid>6d37405b-f708-4940-b2c2-0bc1814a927a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='person_panel--select_record_btn']/span</value>
      <webElementGuid>9da1b65d-744f-474f-bd67-16e5847ae9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[3]/following::span[1]</value>
      <webElementGuid>51768dcc-eb42-49ac-9cff-3aec4d8a7273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AND'])[1]/following::span[1]</value>
      <webElementGuid>be601e83-263a-497e-9be1-790028477762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure?'])[2]/preceding::span[1]</value>
      <webElementGuid>24ec527a-5c65-49a5-8cdc-22ae20838df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/preceding::span[1]</value>
      <webElementGuid>40e34ecd-400a-4fe0-93c2-754498e3b367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>06121552-b5b6-4079-a1e9-46708ed536ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/div/button/span</value>
      <webElementGuid>23ef8b7f-f30a-4fb4-a075-7d22810720b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>1d57cc14-47f2-44f8-a1c1-3b8f883e1ebe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
