<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next Button</name>
   <tag></tag>
   <elementGuidId>6277ea6b-39f8-4126-96d1-a19174c9fcc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='person_entry_type_modal--next_button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#person_entry_type_modal--next_button > span.button-inner-container.jss246</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7afa2692-e535-431a-90de-f41937417daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner-container jss246</value>
      <webElementGuid>5347be9b-3edd-4dce-bc4d-cdb5b3a11803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>4a08e509-5c96-4332-9229-1d9e31a543c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;person_entry_type_modal--next_button&quot;)/span[@class=&quot;button-inner-container jss246&quot;]</value>
      <webElementGuid>823af925-ba1c-4e07-bedd-abb11c4bd635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='person_entry_type_modal--next_button']/span</value>
      <webElementGuid>f8fafafc-4c7f-4767-988c-7789be1fd48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/span</value>
      <webElementGuid>efd80cd3-f3f7-4c46-8817-214b065c5619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>c7a70967-5130-49c6-ac54-ec289e7dada2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
