<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Segment Description Text Area</name>
   <tag></tag>
   <elementGuidId>9d536354-1682-4dd8-8d7c-c1d67d15f0cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#segment_create--description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='segment_create--description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>27b0ec2b-d69d-42cf-8ecd-8a7a87957d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segment_create--description</value>
      <webElementGuid>71ac23f4-a00b-4fe0-9970-824d62f1d928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>7325e55b-9fef-4d6d-9d95-da865e532615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ST Segment Test 3192024 Description</value>
      <webElementGuid>05503b93-82be-4cc7-80a0-f156867570c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segment_create--description&quot;)</value>
      <webElementGuid>1f995dcb-aae7-4f1b-b901-400097526220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='segment_create--description']</value>
      <webElementGuid>6189a3f4-2faa-49dd-9f1a-c81aac16a1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::textarea[1]</value>
      <webElementGuid>33972142-56df-4823-92af-dfe50a0af2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::textarea[1]</value>
      <webElementGuid>c8261497-3206-4814-9eec-169d09d4f45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c365a4c4-e319-4659-977b-9cc07e81fb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ST Segment Test 3192024 Description']/parent::*</value>
      <webElementGuid>cf144167-d4a5-40a7-9f86-07c1b89bc9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>790148b1-6238-4b05-8a8c-c016f9a5b034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'segment_create--description' and (text() = 'ST Segment Test 3192024 Description' or . = 'ST Segment Test 3192024 Description')]</value>
      <webElementGuid>64b6bb76-e13d-477e-8d8f-c145af74011f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
