<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Event Save Button</name>
   <tag></tag>
   <elementGuidId>a0708278-2f5e-4ea7-b1a9-9d4303515873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cmui.button.jss207.jss550.jss215.jss206 > span.button-inner-container.jss208 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/main/div/div[2]/section/div/div/button[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bec548f9-8b50-4ae6-bb0c-ddc2ae6c349b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>d8143950-f340-4940-a753-f17e434f4338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss485 jss488 jss473&quot;]/div[@class=&quot;cmui grid jss7 jss474&quot;]/div[@class=&quot;container&quot;]/section[@class=&quot;jss524&quot;]/div[@class=&quot;jss523&quot;]/div[@class=&quot;jss525&quot;]/button[@class=&quot;cmui button jss207 jss550 jss215 jss206&quot;]/span[@class=&quot;button-inner-container jss208&quot;]/span[1]</value>
      <webElementGuid>799b0af9-6a37-4d0f-a670-285e2c2ceb63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/div[2]/section/div/div/button[2]/span/span</value>
      <webElementGuid>f8b923ff-4a79-45ec-aef2-f6ce67a3220f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[2]</value>
      <webElementGuid>aa11a435-196c-4b2e-8fd3-277e778084d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Count'])[3]/following::span[6]</value>
      <webElementGuid>26e91ce4-308b-491f-a6fb-a8dd75cc3bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Milestones'])[1]/preceding::span[1]</value>
      <webElementGuid>bed1069a-4650-4b65-b67c-edb82bbb3759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[8]/preceding::span[2]</value>
      <webElementGuid>98fd1543-04d4-42fe-8ea0-46f718b467db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>198bf223-a8da-4edf-9299-316923681b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>7befaa43-fb48-44bc-ae3d-597bb468325d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>0b887987-6573-4e96-b0eb-abfcebb97bac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
