<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yes</name>
   <tag></tag>
   <elementGuidId>4262546b-3928-488f-91f8-474aacf5c69f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Yes' or . = 'Yes')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.prompt-yes-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95d87bc9-aabc-4c6f-b912-5efed2c71293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prompt-yes-btn</value>
      <webElementGuid>cc2907a8-0c5e-4269-b998-01b7fd487899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>063571d9-da16-45e2-b9e9-edb6b2e3a6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46ddadd8-f85a-4a78-894a-e7166c7068e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>95909fec-8944-417e-969a-35a7238d0dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;page-content&quot;]/div[1]/main[@class=&quot;ui page jss277 jss280 page-has_action_bar&quot;]/div[@class=&quot;cmui container jss306 ui page--container jss305&quot;]/section[@class=&quot;cmui content jss309 ui page--content jss308&quot;]/div[@class=&quot;jss271&quot;]/div[@class=&quot;ui page--data_groups&quot;]/div[@class=&quot;page--data_groups_column&quot;]/div[@class=&quot;page--data_group&quot;]/div[@class=&quot;page--data_group_inner_container&quot;]/div[@class=&quot;page--data_group_contract_section&quot;]/div[@class=&quot;ui list page--data_group_list list-divide&quot;]/div[@class=&quot;list--item&quot;]/div[@class=&quot;page--data_group_row&quot;]/div[@class=&quot;page--data_group_row_value&quot;]/ul[@class=&quot;jss275&quot;]/li[@class=&quot;jss272&quot;]/div[@class=&quot;ui prompt jss358 prompt-show prompt-inline&quot;]/div[@class=&quot;prompt-actions jss357&quot;]/div[@class=&quot;prompt-yes-btn&quot;]</value>
      <webElementGuid>21b23e3b-a165-4251-8511-4d8fab1bbc37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div[2]/div/div/div/div/div[2]/div/div[7]/div/div/ul/li/div[2]/div[2]/div[2]</value>
      <webElementGuid>e446f496-b784-4d9d-869f-ae82ac758119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>cbf5a25d-2896-4800-9ad8-6379d6e6d415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>06ee8781-9563-4a26-81b7-21e704a5f332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
