<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Unpublish</name>
   <tag></tag>
   <elementGuidId>3c69c010-eb4a-49fd-9bfc-4ebe61cd93a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='connection_forms--details--publish_unpublish_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection_forms--details--publish_unpublish_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>22759661-ecbc-40a5-a6bf-9ccfb5e1eaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui a jss358 jss273</value>
      <webElementGuid>e28bfdf1-480e-46f1-87e7-1a1fe823979f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection_forms--details--publish_unpublish_link</value>
      <webElementGuid>fc4c7108-f2fe-49a6-953d-a5bb7254828a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64c63ed7-13ef-4620-a510-8b9566b16d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>97d1f40d-9e6c-4ff3-8294-b1b4fe52502d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unpublish</value>
      <webElementGuid>f8695b94-72cc-4c63-b64f-12e661ab567b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection_forms--details--publish_unpublish_link&quot;)</value>
      <webElementGuid>b35ac254-e7b2-469a-ac63-5b8fa18a06be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='connection_forms--details--publish_unpublish_link']</value>
      <webElementGuid>71c9bbfc-d616-4853-9470-5598f6af1262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/section/div[2]/div/div/div/div/div[2]/div/div[7]/div/div/ul/li[3]/div/div/span</value>
      <webElementGuid>1b0a9443-f90a-42d4-a174-dc63e6f49161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/span</value>
      <webElementGuid>c3f24de2-863b-4320-ae97-3e7d17f5076a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'connection_forms--details--publish_unpublish_link' and (text() = 'Unpublish' or . = 'Unpublish')]</value>
      <webElementGuid>2b894c60-e3ed-4ff1-86fb-67ad538ac98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
