<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>91027353-bc17-43ee-8b82-98b0a340b363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='person_panel--select_record_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#person_panel--select_record_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>020ded1b-6cdf-469f-9ae1-12a2a421b4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui button jss207 jss1186 person_panel--details_action_button jss1184 jss212 jss206</value>
      <webElementGuid>6f3bf29d-59c8-4b35-8021-645e3ed7f4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>person_panel--select_record_btn</value>
      <webElementGuid>a63ea1cf-5b0d-428e-b628-984dff605344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f8134af-60b3-408e-b236-c7f67f128ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>6109a377-e557-4bba-bb49-ae906748f646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;people_search_drawer--results&quot;)/div[@class=&quot;jss1141 jss1136 cmui person_panel&quot;]/div[@class=&quot;jss1168 jss1134 jss1139 cmui person_panel--details jss1166&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[@class=&quot;jss1165&quot;]/div[@class=&quot;jss1163&quot;]/div[@class=&quot;ui prompt jss498 jss1185 prompt-inline&quot;]/div[1]/button[@id=&quot;person_panel--select_record_btn&quot;]</value>
      <webElementGuid>747d4296-62fe-4c9b-bf29-5260e5014f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='person_panel--select_record_btn']</value>
      <webElementGuid>ba600799-dc25-481d-98a5-567dd921a152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='people_search_drawer--results']/div/div[2]/div/div/div/div/div[3]/div/div/button</value>
      <webElementGuid>74e0111d-236e-484c-93a6-d799de5b3fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[1]/following::button[1]</value>
      <webElementGuid>cf950961-2e12-45c6-8c72-5dbfd59df08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sam@jay.com'])[1]/following::button[1]</value>
      <webElementGuid>7477f673-6c22-46ad-be19-3077bca7f99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure?'])[1]/preceding::button[1]</value>
      <webElementGuid>41e5d30e-c34f-4b7d-b1d1-32e92c244736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div[3]/div/div/button</value>
      <webElementGuid>544edd85-67d4-4aae-bded-9b78afca265f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'person_panel--select_record_btn' and @type = 'button' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>9f974f55-4625-4169-9a84-d1af0bbbf4a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
