<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Export Button</name>
   <tag></tag>
   <elementGuidId>742ded7d-cdcf-4659-8066-07a2a6168253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-button--segment-export > span.button-inner-container.jss208 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ui-button--segment-export']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;spreadsheet Export&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4673eeea-7a35-4f92-9c1f-c8b77775c121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export</value>
      <webElementGuid>06fc8e3a-37b1-44df-8a00-42b8a8da3644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-button--segment-export&quot;)/span[@class=&quot;button-inner-container jss208&quot;]/span[1]</value>
      <webElementGuid>4d9ce6a3-f610-4b3e-abcf-ab775551a372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ui-button--segment-export']/span/span</value>
      <webElementGuid>e485dd73-fb86-47e0-93df-4ea645c01f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate'])[1]/following::span[2]</value>
      <webElementGuid>0b2904f1-4c60-4590-ba4c-33df659ec7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::span[4]</value>
      <webElementGuid>8406b5d2-eef4-4591-b238-8f5fae12fdfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST Segment Record 1'])[2]/preceding::span[1]</value>
      <webElementGuid>33ceb84c-55c2-49c3-9abc-740ebf1e1251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST Segment Record 1 Description'])[1]/preceding::span[1]</value>
      <webElementGuid>1738f130-02b8-4228-a133-53484bd0d070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Export']/parent::*</value>
      <webElementGuid>7a69ac17-481b-4989-8767-04db193cb44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span/span</value>
      <webElementGuid>07eb3a63-9e3f-4ecc-b921-ec36f0ec84b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Export' or . = 'Export')]</value>
      <webElementGuid>6844bb42-5156-4309-9976-8b73bdfdd836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
