<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>XLSX Download Link</name>
   <tag></tag>
   <elementGuidId>1ef45019-afb4-4cfc-92b5-850e273265d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jss242</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Download')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Download&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6efb403-60fd-4ddd-bdb3-75114338ad44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss242</value>
      <webElementGuid>59da657a-a364-4074-9b30-49e843c41616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hc-dev.saddleback.com/api/export/Segment?file=SegmentDataExtract_2024-04-15_07_21_09.xlsx&amp;token=e5e9e33e-c1b9-004c-0d00-0000797b11f8&amp;format=Excel</value>
      <webElementGuid>be941ad4-866c-43db-81c8-b4469618022a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>c18fda80-3637-4137-9e7c-332ca0be9d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f692bf9e-7049-4d7c-a768-0fb1f0654840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>0cae922f-da8c-4fe4-96f8-9a237c3736ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;safari&quot;]/body[1]/div[6]/div[@class=&quot;ui banner jss241 banner-level-success banner-type-notification&quot;]/div[@class=&quot;banner-container jss241&quot;]/div[@class=&quot;banner-message-container&quot;]/a[@class=&quot;jss242&quot;]</value>
      <webElementGuid>1912ebbb-0fd0-43b6-b097-420339881ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>29c1db47-de2b-4648-9439-e44f11503038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your file is ready for download'])[1]/following::a[1]</value>
      <webElementGuid>99e56a55-0d8a-4333-a4fe-65cfbe0566fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>5df1d0e9-eb33-402e-a336-5d5404724795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hc-dev.saddleback.com/api/export/Segment?file=SegmentDataExtract_2024-04-15_07_21_09.xlsx&amp;token=e5e9e33e-c1b9-004c-0d00-0000797b11f8&amp;format=Excel')]</value>
      <webElementGuid>1b52095a-72a7-4cae-94b7-088cf8c1e08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7aa6c4f2-203b-415c-9a40-d88f9a679e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hc-dev.saddleback.com/api/export/Segment?file=SegmentDataExtract_2024-04-15_07_21_09.xlsx&amp;token=e5e9e33e-c1b9-004c-0d00-0000797b11f8&amp;format=Excel' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>6f8cc71f-ee8b-421e-b22f-b614dc115f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
