<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Language Label</name>
   <tag></tag>
   <elementGuidId>8ee5d13e-0816-4965-8ea8-b7493109afe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Language' or . = 'Language')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c81e829d-1d5a-44df-9c2f-0c5745b42ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>headerLangSelect</value>
      <webElementGuid>1bafb615-b3d7-47e4-a154-5c4b7f96c4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>09cbdfc6-1216-44d1-9568-e84dbd21e545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;header-lang-select-div desktop-center&quot;]/div[@class=&quot;header-lang-select&quot;]/label[1]</value>
      <webElementGuid>8d5b720f-e2c3-470a-91ac-d0b2bb99c559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c18ef1e6-a57c-41ee-bc12-b1f7c1571fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Language' or . = 'Language')]</value>
      <webElementGuid>07d812f3-3a00-4b8b-ac55-da537c7bd5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
