<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Volunteer Button</name>
   <tag></tag>
   <elementGuidId>fc5b7a7a-f82d-452e-9920-b27745d216b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='serving_opportunities--dropdown_button' and not(@disabled)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serving_opportunities--dropdown_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63987171-24cb-410c-b5bd-0ff94dda6075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aa9bd133-5b0f-420b-9f7c-01dab199f678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui button jss207 jss2027 jss205 button_dropdown jss215 jss217 jss206</value>
      <webElementGuid>36e37c31-b703-47cb-b99f-0ccce6ebb9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serving_opportunities--dropdown_button</value>
      <webElementGuid>e65b7391-596e-466f-9343-c67ddb971d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>038e04da-77a7-4821-b4ac-908a5aa99ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>plusAdd VolunteerTo This OccurrenceTo All Occurrences</value>
      <webElementGuid>c305d478-fad8-4d6c-86e2-965d3a7354f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serving_opportunities--dropdown_button&quot;)</value>
      <webElementGuid>f948b38d-7776-4ed3-a778-23bba3c51d85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
