<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Text Field</name>
   <tag></tag>
   <elementGuidId>6a266cd1-099a-47d2-aeed-26b0b9a85255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#segment--search_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='push_notification--search_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e3cb472-33bd-4eee-a0ff-e481c57c0ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cmui--search_input</value>
      <webElementGuid>35e3e773-d510-4279-a2e9-70cc1323989a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segment--search_input</value>
      <webElementGuid>31d4a7d0-c55a-4ddc-aaa1-14937d83b9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d1dfc16f-5e1b-40fa-85c8-7e72ec3e05a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5883096-4077-4884-a63b-cf6b23ad819d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segment--search_input&quot;)</value>
      <webElementGuid>3945ce68-76f3-449f-8009-1a9d6837ac6e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
