<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Segment Save Button</name>
   <tag></tag>
   <elementGuidId>ef4cfc80-10f2-4154-b85e-adbcd8a9101b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#segment_primary_details_edit__save_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='segment_primary_details_edit__save_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc9b76a0-5118-4ddf-bcc2-6b70c1dd41b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6cab8af8-38d5-474b-b0f7-c98aa19118cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmui button jss207 jss535 jss215 jss206</value>
      <webElementGuid>d2b10701-0cee-4c6b-9dc4-b5da329ad4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segment_primary_details_edit__save_button</value>
      <webElementGuid>cd3be8c1-2274-42e4-bef0-f780f84cde64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c841d083-4ae0-4899-be55-2662babb65ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>693e8b6d-8a41-4c39-8d66-f9a95500f3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segment_primary_details_edit__save_button&quot;)</value>
      <webElementGuid>b3d5bcd6-d456-4d22-acec-fd7049c5763e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='segment_primary_details_edit__save_button']</value>
      <webElementGuid>5f0cd64b-0594-4652-bee4-da11372da42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>5896082b-a769-440c-806a-72f4ed09ffd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Segment Info'])[1]/following::button[2]</value>
      <webElementGuid>54d5db95-fc7b-40c1-a04c-95d515c1ac4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segment Info'])[1]/preceding::button[1]</value>
      <webElementGuid>cb95d39c-da11-4209-a6d5-fec216669ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div[2]/button</value>
      <webElementGuid>de5c5f51-557f-475a-a209-b6f402ce5d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'segment_primary_details_edit__save_button' and @type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>28f76a0f-39bf-4881-9ba2-d79f30103e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
