<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_4</name>
   <tag></tag>
   <elementGuidId>8572987f-324b-48e9-a754-50dce31e48da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div/div/div[9]/div/div/div[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5bcc7f96-24cd-4bbe-8fb9-98bc664d72e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label jss481</value>
      <webElementGuid>aa690fdb-97b6-48a7-92f6-31c539f89ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>22b17c56-862d-4a9e-82b3-f7b86ce7bce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[1]/div[@class=&quot;jss3&quot;]/div[@class=&quot;jss484&quot;]/div[1]/div[@class=&quot;cmui grid--column jss309 jss487 jss332&quot;]/div[@class=&quot;ui radio jss483 jss494 jss478 radio-full-width&quot;]/label[@class=&quot;label jss481&quot;]</value>
      <webElementGuid>65cee687-024a-474f-92ea-bbf9f814f8cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div/div/div[9]/div/div/div[5]/label</value>
      <webElementGuid>cea5cace-833f-4c62-b567-b18f4658d6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label</value>
      <webElementGuid>8eab861b-facb-4b2b-89dc-f910b209d672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '4' or . = '4')]</value>
      <webElementGuid>6edaa7a5-cab4-46d5-bfc6-51608b23e7d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
