<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_None</name>
   <tag></tag>
   <elementGuidId>e6968685-e535-40f1-9088-15c58496cb14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='task_action_form']/div[10]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.label.jss435</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ef1481a0-9138-4277-a934-f77f94b3a457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label jss435</value>
      <webElementGuid>cfc21ccc-0ab4-45d2-b367-01f870b483e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>bf68d039-9f2e-4687-89ec-ba1ad0325ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_action_form&quot;)/div[@class=&quot;cmui grid--column jss45&quot;]/div[@class=&quot;ui radio jss437 jss422 jss432 radio-full-width&quot;]/label[@class=&quot;label jss435&quot;]</value>
      <webElementGuid>8b70df02-af15-4a8f-88de-9d25d377b311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task_action_form']/div[10]/div[2]/label</value>
      <webElementGuid>29b2a1f1-76b0-4405-a8d6-f685217895e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/following::label[1]</value>
      <webElementGuid>a586c6c4-27d6-4412-8ca4-541af1cc32f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[2]/following::label[1]</value>
      <webElementGuid>b9c416e8-cb1c-4c75-b8d9-51e07f120215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Batch'])[1]/preceding::label[1]</value>
      <webElementGuid>5ec6af88-adfe-40d3-96e7-47834db87046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/label</value>
      <webElementGuid>0c9ac423-9c3d-4550-811e-9ccf9049c4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'None' or . = 'None')]</value>
      <webElementGuid>fd492e80-4013-4c9f-8cd0-7578b103e8a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
