<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Segment Description Text Area</name>
   <tag></tag>
   <elementGuidId>81a7f732-156b-4825-9554-f87d880671e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#segment_primary_details_edit--description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='segment_primary_details_edit--description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0f613bae-1c1a-4081-bf9d-860384a74bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segment_primary_details_edit--description</value>
      <webElementGuid>84145d9e-8995-45c6-8bbf-9e880fd89249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>3c115767-6249-4fd2-9e03-305c0971f1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ST Record 1 Description Edited</value>
      <webElementGuid>e7e69c0f-b290-4635-897f-a413763b0a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segment_primary_details_edit--description&quot;)</value>
      <webElementGuid>21daadaa-5104-46dc-907f-22e5fc56eec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='segment_primary_details_edit--description']</value>
      <webElementGuid>b656ad90-166c-4e6c-a6fa-5d742c53da2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::textarea[1]</value>
      <webElementGuid>d6a3f3fb-4bf2-4158-a496-2235fa73fb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::textarea[1]</value>
      <webElementGuid>fbbfaa86-1cb9-41d2-aa48-e79ca675592e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campus'])[2]/preceding::textarea[1]</value>
      <webElementGuid>d7229444-0c45-4519-b821-1ab5a6ed0bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anaheim'])[2]/preceding::textarea[1]</value>
      <webElementGuid>acd9d66e-e856-45ac-8a1c-966d0a1eb96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ST Record 1 Description Edited']/parent::*</value>
      <webElementGuid>ea30a35e-104a-43e8-b202-213f6e80243c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5dc54582-5afd-46a0-a4cb-9baa46f39703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'segment_primary_details_edit--description' and (text() = 'ST Record 1 Description Edited' or . = 'ST Record 1 Description Edited')]</value>
      <webElementGuid>2cb9c684-197f-4afa-bb6f-61ca793152e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
