<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputjourneys_list_page--step_form_title</name>
   <tag></tag>
   <elementGuidId>080a7151-50c3-4934-9eb2-e26985ed9425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='journeys_list_page--step_form_title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#journeys_list_page--step_form_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c1d3cbf-26b4-45ef-9972-5fcc70914b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>journeys_list_page--step_form_title</value>
      <webElementGuid>5dad9ea5-0911-43ff-8938-df2548ca9b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New Section</value>
      <webElementGuid>037e2583-b448-4f7d-8f42-68cd1a728ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0bd55b4b-4c99-4a99-ad15-9dc64b2ed218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3084137d-ec74-4d6c-9eea-6f5d8d0fb4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;journeys_list_page--step_form_title&quot;)</value>
      <webElementGuid>4f601408-aeff-4125-be13-be4ebf1d1d7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='journeys_list_page--step_form_title']</value>
      <webElementGuid>2a5dd498-123e-4a86-b1ee-819a6db4447d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/main/div/div/div/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>c46623da-5411-4ead-ab2b-57cf92a9b575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>d6c0d50a-1823-4c4a-a062-1da91757898e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'journeys_list_page--step_form_title' and @placeholder = 'New Section' and @type = 'text']</value>
      <webElementGuid>a59aa942-b26b-4294-93c8-6f7e36bdc4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
