<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DrawerHeader</name>
   <tag></tag>
   <elementGuidId>200c2b58-87c5-414f-a2a1-4a5d9f9a6009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//header[@class=&quot;drawer-header&quot;]/h2)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
