<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>396a0d9c-1b23-4e07-b0bf-5598a31c294b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ui-button--new_announcement_add_announcements']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-button--new_announcement_add_announcements > span.button-inner-container.jss246</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0040f639-90ec-48c3-a177-75b5388e9be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner-container jss246</value>
      <webElementGuid>266bff55-1b76-4632-8923-3c840793cf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>ce72b4ef-5bf2-4cf0-86f0-c4cceed79ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-button--new_announcement_add_announcements&quot;)/span[@class=&quot;button-inner-container jss246&quot;]</value>
      <webElementGuid>44556bc2-e775-4c0e-ab99-1f1862979020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ui-button--new_announcement_add_announcements']/span</value>
      <webElementGuid>0e79859d-91c0-4d3d-b1e7-afc0efc73373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/span</value>
      <webElementGuid>c122ef66-4b2b-435d-b1a2-52c7025b2390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>4dbfdda2-01b1-4b64-ac49-d4c867ceb987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
